"""Enums for Operator Review Policy Guard projections."""
from __future__ import annotations

from enum import Enum

CONTRACT_VERSION = "operator-review-policy-guard.v1"


class GuardState(str, Enum):
    ALLOWED_FOR_REVIEW_ONLY = "ALLOWED_FOR_REVIEW_ONLY"
    BLOCKED_BY_POLICY = "BLOCKED_BY_POLICY"
    BLOCKED_BY_PRECONDITION = "BLOCKED_BY_PRECONDITION"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class EligibilityState(str, Enum):
    ELIGIBLE_FOR_PREVIEW = "ELIGIBLE_FOR_PREVIEW"
    NOT_ELIGIBLE_FOR_EXECUTION = "NOT_ELIGIBLE_FOR_EXECUTION"
    BLOCKED = "BLOCKED"
    REVIEW_ONLY = "REVIEW_ONLY"


class PolicyResult(str, Enum):
    PASS_READ_ONLY = "PASS_READ_ONLY"
    FAIL_WRITE_NOT_AUTHORIZED = "FAIL_WRITE_NOT_AUTHORIZED"
    FAIL_APPROVAL_NOT_AUTHORIZED = "FAIL_APPROVAL_NOT_AUTHORIZED"
    FAIL_RUNTIME_NOT_AUTHORIZED = "FAIL_RUNTIME_NOT_AUTHORIZED"
    FAIL_PRECONDITION_MISSING = "FAIL_PRECONDITION_MISSING"


class AuditPreviewState(str, Enum):
    GENERATED_READ_ONLY = "GENERATED_READ_ONLY"
    BLOCKED = "BLOCKED"
    NOT_GENERATED = "NOT_GENERATED"


class AuditEventType(str, Enum):
    DECISION_PREVIEW = "DECISION_PREVIEW"
    APPROVAL_PREVIEW = "APPROVAL_PREVIEW"
    REJECTION_PREVIEW = "REJECTION_PREVIEW"
    DEFER_PREVIEW = "DEFER_PREVIEW"
    POLICY_GUARD_PREVIEW = "POLICY_GUARD_PREVIEW"


class ActorPolicy(str, Enum):
    OPERATOR_REQUIRED = "OPERATOR_REQUIRED"
    SUPERVISOR_REQUIRED = "SUPERVISOR_REQUIRED"
    ADMIN_REQUIRED = "ADMIN_REQUIRED"
    SYSTEM_NOT_ALLOWED = "SYSTEM_NOT_ALLOWED"
    UNKNOWN = "UNKNOWN"
