"""Enums for UConsole Operator Review Queue projections."""
from __future__ import annotations

from enum import Enum

CONTRACT_VERSION = "uconsole-operator-review-queue-projection.v1"


class QueueStatus(str, Enum):
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    BLOCKED = "BLOCKED"
    PENDING = "PENDING"
    EMPTY = "EMPTY"
    UNKNOWN = "UNKNOWN"


class QueueCardType(str, Enum):
    ALL_PENDING_SUMMARY = "ALL_PENDING_SUMMARY"
    SOURCE_SYSTEM_REVIEW_SUMMARY = "SOURCE_SYSTEM_REVIEW_SUMMARY"
    ASSET_RESOLUTION_SUMMARY = "ASSET_RESOLUTION_SUMMARY"
    ALARM_EVENT_REVIEW_SUMMARY = "ALARM_EVENT_REVIEW_SUMMARY"
    FAULTCASE_REVIEW_SUMMARY = "FAULTCASE_REVIEW_SUMMARY"
    WORKORDER_INTENT_REVIEW_SUMMARY = "WORKORDER_INTENT_REVIEW_SUMMARY"
    EVIDENCE_INVESTIGATION_REVIEW_SUMMARY = "EVIDENCE_INVESTIGATION_REVIEW_SUMMARY"
    RELEASE_GATE_SUMMARY = "RELEASE_GATE_SUMMARY"


class Severity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
