"""Frozen constants for airport review projection."""
from __future__ import annotations

AUTHORITY = "ONE-AIRPORT-A1-05"
PROFILE_ID = "airport-asset-review-projection-v1"
PROFILE_NAME = "VANTARIS ONE Airport Reconciled Asset Review Projection"
PROFILE_VERSION = "1.0.0"
IMPLEMENTATION_MODE = "READ_ONLY_PROJECTION"

RECONCILIATION_AUTHORITY = "ONE-AIRPORT-A1-04"
RECONCILIATION_PROFILE_VERSION = "1.0.0"

FORBIDDEN_READINESS = frozenset(
    {
        "READY_FOR_DATABASE_IMPORT",
        "READY_FOR_CANONICAL_WRITE",
        "READY_FOR_WRITE_CUTOVER",
    }
)

READINESS_OUTCOMES = frozenset(
    {
        "REVIEW_PROJECTION_BLOCKED",
        "REVIEW_PROJECTION_COMPLETE_WITH_PENDING_DECISIONS",
        "READY_FOR_READ_ONLY_UCONSOLE_INTEGRATION",
    }
)

DISPLAY_STATUS_PRIORITY: tuple[str, ...] = (
    "BLOCKED",
    "DUPLICATE_DECISION_REQUIRED",
    "CONTEXT_REQUIRED",
    "NAMESPACE_REVIEW_REQUIRED",
    "ALIAS_APPROVAL_REQUIRED",
    "LABEL_REVIEW_REQUIRED",
    "LOCATION_REVIEW_REQUIRED",
    "REVIEW_REQUIRED",
    "READY_FOR_REVIEW",
    "EVIDENCE_COMPLETE",
)

PAGE_SIZE_OPTIONS = (25, 50, 100)
MAX_PAGE_SIZE = 200

GATE_IDS = (
    "G01_INPUT_EVIDENCE_INTEGRITY",
    "G02_RECORD_COUNT_ALIGNMENT",
    "G03_SPATIAL_BINDING_COVERAGE",
    "G04_CLASSIFICATION_EVIDENCE_COVERAGE",
    "G05_DUPLICATE_IDENTITY_REVIEW",
    "G06_SYSTEM_ALIAS_APPROVAL",
    "G07_SOURCE_NAMESPACE_APPROVAL",
    "G08_DEVICE_LABEL_NORMALIZATION",
    "G09_LOCATION_RECONCILIATION",
    "G10_CONTEXT_APPROVAL",
    "G11_CANONICAL_PROPOSAL_COMPLETENESS",
    "G12_WRITE_BOUNDARY_ENFORCEMENT",
)

INFORMATIONAL_LOCATION_STATUSES = frozenset(
    {
        "EXPECTED_SHARED_LOCATION",
        "NORMALIZED_LOCATION_REUSE",
    }
)

PENDING_LOCATION_STATUSES = frozenset(
    {
        "LOCATION_CONFLICT_REVIEW",
        "SEMANTIC_MERGE_APPROVAL_REQUIRED",
        "NORMALIZED_LOCATION_TEXT_COLLISION",
    }
)
