"""Enums for the Operator Review Decision Layer."""
from __future__ import annotations

from enum import Enum

CONTRACT_VERSION = "operator-review-decision-layer.v1"


class DecisionType(str, Enum):
    REGISTRY_APPROVAL = "REGISTRY_APPROVAL"
    ALIAS_APPROVAL = "ALIAS_APPROVAL"
    NAMESPACE_INTERPRETATION = "NAMESPACE_INTERPRETATION"
    ASSET_RESOLUTION = "ASSET_RESOLUTION"
    POINT_RESOLUTION = "POINT_RESOLUTION"
    LOCATION_RESOLUTION = "LOCATION_RESOLUTION"
    ALARM_EVENT_REVIEW = "ALARM_EVENT_REVIEW"
    FAULTCASE_CANDIDATE_REVIEW = "FAULTCASE_CANDIDATE_REVIEW"
    WORKORDER_INTENT_REVIEW = "WORKORDER_INTENT_REVIEW"
    EVIDENCE_INVESTIGATION_REVIEW = "EVIDENCE_INVESTIGATION_REVIEW"
    DOWNSTREAM_CREATION_AUTHORIZATION = "DOWNSTREAM_CREATION_AUTHORIZATION"
    RELEASE_GATE_REVIEW = "RELEASE_GATE_REVIEW"
    UNKNOWN = "UNKNOWN"


class DecisionScope(str, Enum):
    ASSET_REVIEW = "ASSET_REVIEW"
    SOURCE_SYSTEM_REVIEW = "SOURCE_SYSTEM_REVIEW"
    INTEGRATION_HEALTH_REVIEW = "INTEGRATION_HEALTH_REVIEW"
    ALARM_EVENT_REVIEW = "ALARM_EVENT_REVIEW"
    FAULTCASE_REVIEW = "FAULTCASE_REVIEW"
    WORKORDER_REVIEW = "WORKORDER_REVIEW"
    EVIDENCE_REVIEW = "EVIDENCE_REVIEW"
    RELEASE_GATE = "RELEASE_GATE"
    UNKNOWN = "UNKNOWN"


class DecisionState(str, Enum):
    PENDING = "PENDING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    BLOCKED = "BLOCKED"
    DEFERRED = "DEFERRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class QueueType(str, Enum):
    SOURCE_SYSTEM_QUEUE = "SOURCE_SYSTEM_QUEUE"
    ASSET_RESOLUTION_QUEUE = "ASSET_RESOLUTION_QUEUE"
    ALARM_EVENT_QUEUE = "ALARM_EVENT_QUEUE"
    FAULTCASE_QUEUE = "FAULTCASE_QUEUE"
    WORKORDER_INTENT_QUEUE = "WORKORDER_INTENT_QUEUE"
    EVIDENCE_INVESTIGATION_QUEUE = "EVIDENCE_INVESTIGATION_QUEUE"
    RELEASE_GATE_QUEUE = "RELEASE_GATE_QUEUE"
    ALL_PENDING_QUEUE = "ALL_PENDING_QUEUE"


class Severity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
