"""Controlled states for Evidence Investigation projections."""
from __future__ import annotations

from enum import Enum

CONTRACT_VERSION = "evidence-investigation-projection.v1"


class InvestigationState(str, Enum):
    CANDIDATE = "CANDIDATE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    REJECTED = "REJECTED"


class EvidenceCompletenessState(str, Enum):
    COMPLETE_FOR_REVIEW = "COMPLETE_FOR_REVIEW"
    PARTIAL = "PARTIAL"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"


class LinkageState(str, Enum):
    LINKED = "LINKED"
    PARTIAL = "PARTIAL"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"


class EvidenceRole(str, Enum):
    SOURCE_EVENT = "SOURCE_EVENT"
    RESOLUTION_EVIDENCE = "RESOLUTION_EVIDENCE"
    FAULTCASE_CANDIDATE_EVIDENCE = "FAULTCASE_CANDIDATE_EVIDENCE"
    WORKORDER_INTENT_EVIDENCE = "WORKORDER_INTENT_EVIDENCE"
    SOURCE_SYSTEM_REVIEW_EVIDENCE = "SOURCE_SYSTEM_REVIEW_EVIDENCE"
    UCONSOLE_CONTEXT = "UCONSOLE_CONTEXT"
    UNKNOWN = "UNKNOWN"


class TimelineItemType(str, Enum):
    ALARM_EVENT_CANDIDATE = "ALARM_EVENT_CANDIDATE"
    RESOLUTION_REVIEW = "RESOLUTION_REVIEW"
    FAULTCASE_CANDIDATE = "FAULTCASE_CANDIDATE"
    WORKORDER_INTENT_CANDIDATE = "WORKORDER_INTENT_CANDIDATE"
    SOURCE_SYSTEM_REVIEW = "SOURCE_SYSTEM_REVIEW"
    INVESTIGATION_CONTEXT = "INVESTIGATION_CONTEXT"
