import type { AppMenuItem } from './types'

export const fallbackMenuItems: AppMenuItem[] = [
  { id: 'dashboard', label: 'Dashboard', path: '/dashboard', source: 'static' },
  {
    id: 'system',
    label: 'System',
    path: '/system',
    source: 'static',
    children: [
      { id: 'system-overview', label: 'System Overview', path: '/system', source: 'static' },
      {
        id: 'system-permissions',
        label: 'Permission Management',
        path: '/system/permissions',
        source: 'static',
      },
      {
        id: 'system-settings',
        label: 'System Settings',
        path: '/system/settings',
        source: 'static',
      },
      {
        id: 'system-audit-logs',
        label: 'Audit Logs',
        path: '/system/audit-logs',
        source: 'static',
      },
      {
        id: 'system-notification-settings',
        label: 'Notification Settings',
        path: '/system/notification-settings',
        source: 'static',
      },
      {
        id: 'system-integration-settings',
        label: 'Integration Settings',
        path: '/system/integration-settings',
        source: 'static',
      },
    ],
  },
  { id: 'iot', label: 'IoT', path: '/iot', source: 'static' },
  { id: 'did', label: 'DID', path: '/did', source: 'static' },
  { id: 'modeling', label: 'Modeling', path: '/modeling', source: 'static' },
  {
    id: 'uconsole',
    label: 'UConsole',
    path: '/console/operations',
    source: 'static',
    children: [
      {
        id: 'uconsole-platform-operations',
        label: 'Platform Operations',
        path: '/console/operations',
        source: 'static',
      },
      {
        id: 'uconsole-uhmi-workspace',
        label: 'UHMI Workspace',
        path: '/one/uhmi/overview',
        source: 'static',
      },
      {
        id: 'uconsole-engineer-workspace-foundation-diagnostics',
        label: 'Foundation Diagnostics',
        path: '/console/foundation-diagnostics/workspace',
        source: 'static',
      },
      {
        id: 'uconsole-engineer-workspace-package-readiness',
        label: 'Package Readiness',
        path: '/console/foundation-diagnostics/workspace',
        source: 'static',
      },
      {
        id: 'uconsole-engineer-workspace-server-plan',
        label: 'Server Plan',
        path: '/console/foundation-diagnostics/workspace',
        source: 'static',
      },
      {
        id: 'uconsole-engineer-workspace-edge-link-db',
        label: 'EDGE / LINK / DB Diagnostics',
        path: '/console/foundation-diagnostics/workspace',
        source: 'static',
      },
      {
        id: 'uconsole-engineer-workspace-offline-verification',
        label: 'Offline Verification',
        path: '/console/foundation-diagnostics/workspace',
        source: 'static',
      },
      {
        id: 'uconsole-engineer-workspace-rollback-readiness',
        label: 'Rollback Readiness',
        path: '/console/foundation-diagnostics/workspace',
        source: 'static',
      },
    ],
  },
  {
    id: 'assets-topology',
    label: 'Assets & Topology',
    path: '/assets/topology',
    source: 'static',
    children: [
      {
        id: 'assets-topology-home',
        label: 'Asset Topology',
        path: '/assets/topology',
        source: 'static',
      },
    ],
  },
  {
    id: 'ucde',
    label: 'UCDE',
    path: '/ucde/evidence',
    source: 'static',
    children: [
      {
        id: 'ucde-evidence-center',
        label: 'Evidence Center',
        path: '/ucde/evidence',
        source: 'static',
      },
    ],
  },
  {
    id: 'uesg',
    label: 'UESG',
    path: '/uesg/sustainability',
    source: 'static',
    children: [
      {
        id: 'uesg-sustainability',
        label: 'Sustainability',
        path: '/uesg/sustainability',
        source: 'static',
      },
    ],
  },
  {
    id: 'work-management',
    label: 'Work Management',
    path: '/one/umms/workspace',
    source: 'static',
    children: [
      {
        id: 'umms-overview',
        label: 'UMMS Overview',
        path: '/one/umms/workspace',
        source: 'static',
      },
      {
        id: 'umms-work-orders',
        label: 'Work Orders',
        path: '/one/umms/workspace',
        source: 'static',
      },
      {
        id: 'umms-maintenance-tasks',
        label: 'Maintenance Tasks',
        path: '/one/umms/workspace',
        source: 'static',
      },
      {
        id: 'umms-maintenance-plans',
        label: 'Maintenance Plans',
        path: '/one/umms/workspace',
        source: 'static',
      },
      {
        id: 'umms-engineer-dispatch',
        label: 'Engineer Dispatch',
        path: '/one/umms/workspace',
        source: 'static',
      },
      {
        id: 'umms-customer-acceptance',
        label: 'Customer Acceptance',
        path: '/one/umms/workspace',
        source: 'static',
      },
      {
        id: 'umms-evidence-linkage',
        label: 'Evidence Linkage',
        path: '/one/umms/workspace',
        source: 'static',
      },
      {
        id: 'umms-reports',
        label: 'Reports',
        path: '/one/umms/workspace',
        source: 'static',
      },
    ],
  },
  {
    id: 'uedge',
    label: 'UEDGE',
    path: '/uedge/setup',
    source: 'static',
    children: [
      {
        id: 'uedge-setup',
        label: 'Customer Setup',
        path: '/uedge/setup',
        source: 'static',
      },
      {
        id: 'uedge-diagnostics',
        label: 'Engineer Diagnostics',
        path: '/uedge/diagnostics',
        source: 'static',
      },
    ],
  },
  {
    id: 'airport-ga-readonly',
    label: 'Airport GA Read-Only',
    path: '/one/airport/overview',
    source: 'static',
    children: [
      {
        id: 'airport-ga-readonly-overview',
        label: 'Overview',
        path: '/one/airport/overview',
        source: 'static',
      },
      {
        id: 'airport-ga-readonly-health',
        label: 'Systems Health',
        path: '/one/airport/systems-integration-health',
        source: 'static',
      },
      {
        id: 'airport-ga-readonly-assets',
        label: 'Assets & Topology',
        path: '/one/airport/assets-topology',
        source: 'static',
      },
      {
        id: 'airport-ga-readonly-alarms',
        label: 'Alarms & Events',
        path: '/one/airport/alarms-events',
        source: 'static',
      },
      {
        id: 'airport-ga-readonly-faults',
        label: 'Fault Cases',
        path: '/one/airport/fault-cases',
        source: 'static',
      },
      {
        id: 'airport-ga-readonly-workorders',
        label: 'Work Orders',
        path: '/one/airport/maintenance-work-orders',
        source: 'static',
      },
      {
        id: 'airport-ga-readonly-evidence',
        label: 'Evidence & Investigation',
        path: '/one/airport/evidence-investigation',
        source: 'static',
      },
      {
        id: 'airport-ga-readonly-reports',
        label: 'Reports',
        path: '/one/airport/reports',
        source: 'static',
      },
    ],
  },
  { id: 'reports', label: 'Reports', path: '/reports', source: 'static' },
]
