/**
 * UFMS Commercial V1.0 RBAC — permission definitions and role mappings.
 */

export const UFMS_PERMISSION_SEED = [
  { permissionId: 'PERM-084', permissionCode: 'ufms.dashboard.view', permissionName: 'UFMS Dashboard View' },
  { permissionId: 'PERM-085', permissionCode: 'ufms.alarm.view', permissionName: 'UFMS Alarm View' },
  { permissionId: 'PERM-086', permissionCode: 'ufms.alarm.create', permissionName: 'UFMS Alarm Create' },
  { permissionId: 'PERM-087', permissionCode: 'ufms.alarm.acknowledge', permissionName: 'UFMS Alarm Acknowledge' },
  { permissionId: 'PERM-088', permissionCode: 'ufms.alarm.suppress', permissionName: 'UFMS Alarm Suppress' },
  { permissionId: 'PERM-089', permissionCode: 'ufms.alarm.close', permissionName: 'UFMS Alarm Close' },
  { permissionId: 'PERM-090', permissionCode: 'ufms.alarm.convert', permissionName: 'UFMS Alarm Convert' },
  { permissionId: 'PERM-091', permissionCode: 'ufms.episode.view', permissionName: 'UFMS Episode View' },
  { permissionId: 'PERM-092', permissionCode: 'ufms.episode.create', permissionName: 'UFMS Episode Create' },
  { permissionId: 'PERM-093', permissionCode: 'ufms.episode.update', permissionName: 'UFMS Episode Update' },
  { permissionId: 'PERM-094', permissionCode: 'ufms.episode.close', permissionName: 'UFMS Episode Close' },
  { permissionId: 'PERM-095', permissionCode: 'ufms.problem.view', permissionName: 'UFMS Problem View' },
  { permissionId: 'PERM-096', permissionCode: 'ufms.problem.create', permissionName: 'UFMS Problem Create' },
  { permissionId: 'PERM-097', permissionCode: 'ufms.problem.update', permissionName: 'UFMS Problem Update' },
  { permissionId: 'PERM-098', permissionCode: 'ufms.problem.resolve', permissionName: 'UFMS Problem Resolve' },
  { permissionId: 'PERM-099', permissionCode: 'ufms.problem.close', permissionName: 'UFMS Problem Close' },
  { permissionId: 'PERM-100', permissionCode: 'ufms.problem.reopen', permissionName: 'UFMS Problem Reopen' },
  { permissionId: 'PERM-101', permissionCode: 'ufms.workorder.view', permissionName: 'UFMS Work Order View' },
  { permissionId: 'PERM-102', permissionCode: 'ufms.workorder.create', permissionName: 'UFMS Work Order Create' },
  { permissionId: 'PERM-103', permissionCode: 'ufms.workorder.assign', permissionName: 'UFMS Work Order Assign' },
  { permissionId: 'PERM-104', permissionCode: 'ufms.workorder.execute', permissionName: 'UFMS Work Order Execute' },
  { permissionId: 'PERM-105', permissionCode: 'ufms.workorder.close', permissionName: 'UFMS Work Order Close' },
  { permissionId: 'PERM-106', permissionCode: 'ufms.workorder.reopen', permissionName: 'UFMS Work Order Reopen' },
  { permissionId: 'PERM-107', permissionCode: 'ufms.sla.view', permissionName: 'UFMS SLA View' },
  { permissionId: 'PERM-108', permissionCode: 'ufms.sla.manage', permissionName: 'UFMS SLA Manage' },
  { permissionId: 'PERM-109', permissionCode: 'ufms.sop.view', permissionName: 'UFMS SOP View' },
  { permissionId: 'PERM-110', permissionCode: 'ufms.sop.manage', permissionName: 'UFMS SOP Manage' },
  { permissionId: 'PERM-111', permissionCode: 'ufms.inspection.view', permissionName: 'UFMS Inspection View' },
  { permissionId: 'PERM-112', permissionCode: 'ufms.inspection.manage', permissionName: 'UFMS Inspection Manage' },
  { permissionId: 'PERM-113', permissionCode: 'ufms.inspection.execute', permissionName: 'UFMS Inspection Execute' },
  { permissionId: 'PERM-114', permissionCode: 'ufms.inspection.convert', permissionName: 'UFMS Inspection Convert' },
  { permissionId: 'PERM-115', permissionCode: 'ufms.mobile.use', permissionName: 'UFMS Mobile Use' },
  { permissionId: 'PERM-116', permissionCode: 'ufms.requester.submit', permissionName: 'UFMS Requester Submit' },
  { permissionId: 'PERM-117', permissionCode: 'ufms.requester.confirm', permissionName: 'UFMS Requester Confirm' },
  { permissionId: 'PERM-118', permissionCode: 'ufms.requester.reopen', permissionName: 'UFMS Requester Reopen' },
  { permissionId: 'PERM-119', permissionCode: 'ufms.requester.feedback', permissionName: 'UFMS Requester Feedback' },
  { permissionId: 'PERM-120', permissionCode: 'ufms.asset.view', permissionName: 'UFMS Asset View' },
  { permissionId: 'PERM-121', permissionCode: 'ufms.asset.manage', permissionName: 'UFMS Asset Manage' },
  { permissionId: 'PERM-122', permissionCode: 'ufms.asset.analytics', permissionName: 'UFMS Asset Analytics' },
  { permissionId: 'PERM-123', permissionCode: 'ufms.contractor.view', permissionName: 'UFMS Contractor View' },
  { permissionId: 'PERM-124', permissionCode: 'ufms.contractor.manage', permissionName: 'UFMS Contractor Manage' },
  { permissionId: 'PERM-125', permissionCode: 'ufms.sparepart.view', permissionName: 'UFMS Spare Part View' },
  { permissionId: 'PERM-126', permissionCode: 'ufms.sparepart.manage', permissionName: 'UFMS Spare Part Manage' },
  { permissionId: 'PERM-127', permissionCode: 'ufms.sparepart.use', permissionName: 'UFMS Spare Part Use' },
  { permissionId: 'PERM-128', permissionCode: 'ufms.report.view', permissionName: 'UFMS Report View' },
  { permissionId: 'PERM-129', permissionCode: 'ufms.report.export', permissionName: 'UFMS Report Export' },
  { permissionId: 'PERM-130', permissionCode: 'ufms.rfq.view', permissionName: 'UFMS RFQ View' },
  { permissionId: 'PERM-131', permissionCode: 'ufms.rfq.manage', permissionName: 'UFMS RFQ Manage' },
  { permissionId: 'PERM-132', permissionCode: 'ufms.rfq.export', permissionName: 'UFMS RFQ Export' },
  { permissionId: 'PERM-133', permissionCode: 'ufms.connector.view', permissionName: 'UFMS Connector View' },
  { permissionId: 'PERM-134', permissionCode: 'ufms.connector.manage', permissionName: 'UFMS Connector Manage' },
  { permissionId: 'PERM-135', permissionCode: 'ufms.connector.test', permissionName: 'UFMS Connector Test' },
  { permissionId: 'PERM-136', permissionCode: 'ufms.audit.view', permissionName: 'UFMS Audit View' },
  { permissionId: 'PERM-137', permissionCode: 'ufms.settings.manage', permissionName: 'UFMS Settings Manage' },
  { permissionId: 'PERM-138', permissionCode: 'ufms.health.view', permissionName: 'UFMS System Health View' },
  { permissionId: 'PERM-139', permissionCode: 'ufms.health.run', permissionName: 'UFMS System Health Run' },
  { permissionId: 'PERM-140', permissionCode: 'ufms.health.export', permissionName: 'UFMS System Health Export' },
  { permissionId: 'PERM-141', permissionCode: 'ufms.health.server', permissionName: 'UFMS System Health Server Metrics' },
  { permissionId: 'PERM-142', permissionCode: 'ufms.health.protocol', permissionName: 'UFMS System Health Protocol Checks' },
  { permissionId: 'PERM-143', permissionCode: 'ufms.health.maintenance', permissionName: 'UFMS System Health Maintenance Actions' },
  { permissionId: 'PERM-144', permissionCode: 'ufms.health.maintenance.export', permissionName: 'UFMS System Health Maintenance Export' },
  { permissionId: 'PERM-145', permissionCode: 'ufms.health.maintenance.unlock', permissionName: 'UFMS System Health Maintenance Unlock' },
  { permissionId: 'PERM-146', permissionCode: 'ufms.version_control.read', permissionName: 'UFMS Version Control Read' },
  { permissionId: 'PERM-147', permissionCode: 'ufms.version_control.unlock', permissionName: 'UFMS Version Control Unlock' },
  { permissionId: 'PERM-148', permissionCode: 'ufms.version_control.update', permissionName: 'UFMS Version Control Update' },
  { permissionId: 'PERM-149', permissionCode: 'ufms.version_control.audit', permissionName: 'UFMS Version Control Audit' },
  { permissionId: 'PERM-150', permissionCode: 'ufms.rbac_matrix.read', permissionName: 'UFMS RBAC Permission Matrix Read' },
  { permissionId: 'PERM-151', permissionCode: 'ufms.connector_readiness.read', permissionName: 'UFMS Connector Readiness Matrix Read' },
  { permissionId: 'PERM-152', permissionCode: 'ufms.uat_checklist.read', permissionName: 'UFMS Customer UAT Checklist Read' },
  { permissionId: 'PERM-153', permissionCode: 'ufms.uat_checklist.update', permissionName: 'UFMS Customer UAT Checklist Update' },
  { permissionId: 'PERM-154', permissionCode: 'ufms.deployment_handover.read', permissionName: 'UFMS Deployment Handover Checklist Read' },
  { permissionId: 'PERM-155', permissionCode: 'ufms.deployment_handover.update', permissionName: 'UFMS Deployment Handover Checklist Update' },
  { permissionId: 'PERM-156', permissionCode: 'ufms.report_package.read', permissionName: 'UFMS Report Package Read' },
  { permissionId: 'PERM-157', permissionCode: 'ufms.report_package.export', permissionName: 'UFMS Report Package Export' },
  { permissionId: 'PERM-158', permissionCode: 'ufms.system_health.read', permissionName: 'UFMS System Health Diagnostic Read' },
  { permissionId: 'PERM-159', permissionCode: 'ufms.system_health.export', permissionName: 'UFMS System Health Diagnostic Export' },
  { permissionId: 'PERM-160', permissionCode: 'ufms.maintenance_audit.read', permissionName: 'UFMS Maintenance Audit Read' },
  { permissionId: 'PERM-161', permissionCode: 'ufms.rfq_compliance.read', permissionName: 'UFMS RFQ Compliance Matrix Read' },
  { permissionId: 'PERM-162', permissionCode: 'ufms.rfq_compliance.update', permissionName: 'UFMS RFQ Compliance Matrix Update' },
  { permissionId: 'PERM-163', permissionCode: 'ufms.rules_config.read', permissionName: 'UFMS Rules Configuration Read' },
  { permissionId: 'PERM-164', permissionCode: 'ufms.rules_config.update', permissionName: 'UFMS Rules Configuration Update' },
  { permissionId: 'PERM-165', permissionCode: 'ufms.ai_ops.view', permissionName: 'UFMS AI-Assisted Operations View' },
  { permissionId: 'PERM-166', permissionCode: 'ufms.ai.recommendation.view', permissionName: 'UFMS AI Recommendation View' },
  { permissionId: 'PERM-167', permissionCode: 'ufms.ai.recommendation.review', permissionName: 'UFMS AI Recommendation Review' },
  { permissionId: 'PERM-168', permissionCode: 'ufms.ai.rca.view', permissionName: 'UFMS AI RCA View' },
  { permissionId: 'PERM-169', permissionCode: 'ufms.ai.rca.run', permissionName: 'UFMS AI RCA Run' },
] as const

const UFMS_VIEW = [
  'ufms.dashboard.view',
  'ufms.alarm.view',
  'ufms.episode.view',
  'ufms.problem.view',
  'ufms.workorder.view',
  'ufms.sla.view',
  'ufms.sop.view',
  'ufms.inspection.view',
  'ufms.asset.view',
  'ufms.asset.analytics',
  'ufms.contractor.view',
  'ufms.sparepart.view',
  'ufms.report.view',
  'ufms.rfq.view',
  'ufms.connector.view',
  'ufms.audit.view',
  'ufms.ai_ops.view',
  'ufms.ai.recommendation.view',
  'ufms.ai.rca.view',
] as const

const UFMS_FM_MANAGER = [
  ...UFMS_VIEW,
  'ufms.alarm.create',
  'ufms.alarm.acknowledge',
  'ufms.alarm.suppress',
  'ufms.alarm.close',
  'ufms.alarm.convert',
  'ufms.episode.create',
  'ufms.episode.update',
  'ufms.episode.close',
  'ufms.problem.create',
  'ufms.problem.update',
  'ufms.problem.resolve',
  'ufms.problem.close',
  'ufms.problem.reopen',
  'ufms.workorder.create',
  'ufms.workorder.assign',
  'ufms.workorder.execute',
  'ufms.workorder.close',
  'ufms.workorder.reopen',
  'ufms.sla.manage',
  'ufms.sop.manage',
  'ufms.inspection.manage',
  'ufms.inspection.execute',
  'ufms.inspection.convert',
  'ufms.asset.manage',
  'ufms.contractor.manage',
  'ufms.sparepart.manage',
  'ufms.sparepart.use',
  'ufms.report.export',
  'ufms.rfq.manage',
  'ufms.rfq.export',
  'ufms.health.view',
  'ufms.health.run',
  'ufms.health.export',
  'ufms.ai.recommendation.review',
  'ufms.ai.rca.run',
] as const

/** Permissions withheld from Admin (system-level destructive). */
export const ADMIN_EXCLUDED_PERMISSIONS = ['iam:user:disable'] as const

export const UFMS_ROLE_DEFINITIONS = [
  { roleId: 'ROLE-001', roleCode: 'super_admin', roleName: 'Super Admin', description: 'Full system access including destructive IAM actions' },
  { roleId: 'ROLE-002', roleCode: 'admin', roleName: 'Admin', description: 'Full UFMS and platform access except destructive IAM disable' },
  { roleId: 'ROLE-003', roleCode: 'fm_manager', roleName: 'FM Manager', description: 'Facilities management — full UFMS commercial operations' },
  { roleId: 'ROLE-004', roleCode: 'supervisor', roleName: 'Supervisor', description: 'Operational supervision, assign/close work orders, reports' },
  { roleId: 'ROLE-005', roleCode: 'operator', roleName: 'Operator', description: 'Monitor dashboard, triage alarms, create problems and work orders' },
  { roleId: 'ROLE-006', roleCode: 'technician', roleName: 'Technician', description: 'Mobile field execution, evidence, spare parts' },
  { roleId: 'ROLE-007', roleCode: 'contractor', roleName: 'Contractor', description: 'Execute assigned work orders and upload evidence' },
  { roleId: 'ROLE-008', roleCode: 'requester', roleName: 'Requester', description: 'Tenant/requester portal — submit and track requests' },
  { roleId: 'ROLE-009', roleCode: 'auditor', roleName: 'Auditor', description: 'Read-only compliance — dashboard, reports, audit, RFQ' },
  { roleId: 'ROLE-010', roleCode: 'viewer', roleName: 'Viewer', description: 'Limited read-only UFMS access' },
  { roleId: 'ROLE-011', roleCode: 'engineer', roleName: 'Engineer', description: 'Legacy alias — field engineer (maps to technician)' },
] as const

export function buildUfmsRolePermissionCodes(allPermissionCodes: readonly string[]): Record<string, readonly string[]> {
  const all = allPermissionCodes
  const adminCodes = all.filter((c) => !(ADMIN_EXCLUDED_PERMISSIONS as readonly string[]).includes(c))

  return {
    super_admin: all,
    admin: adminCodes,
    fm_manager: [...UFMS_FM_MANAGER],
    supervisor: [
      'ufms.dashboard.view',
      'ufms.alarm.view',
      'ufms.alarm.acknowledge',
      'ufms.alarm.suppress',
      'ufms.alarm.close',
      'ufms.alarm.convert',
      'ufms.episode.view',
      'ufms.episode.create',
      'ufms.episode.update',
      'ufms.problem.view',
      'ufms.problem.create',
      'ufms.problem.update',
      'ufms.problem.resolve',
      'ufms.problem.close',
      'ufms.problem.reopen',
      'ufms.workorder.view',
      'ufms.workorder.create',
      'ufms.workorder.assign',
      'ufms.workorder.execute',
      'ufms.workorder.close',
      'ufms.workorder.reopen',
      'ufms.sla.view',
      'ufms.sop.view',
      'ufms.inspection.view',
      'ufms.asset.view',
      'ufms.asset.analytics',
      'ufms.contractor.view',
      'ufms.sparepart.view',
      'ufms.report.view',
      'ufms.report.export',
      'ufms.rfq.view',
      'ufms.connector.view',
      'ufms.audit.view',
      'ufms.ai_ops.view',
      'ufms.ai.recommendation.view',
      'ufms.ai.recommendation.review',
      'ufms.ai.rca.view',
      'ufms.ai.rca.run',
      'ufms.health.view',
      'ufms.health.run',
      'ufms.health.export',
      'ufms.system_health.read',
      'ufms.system_health.export',
      'ufms.maintenance_audit.read',
      'ufms.rfq_compliance.read',
      'ufms.rfq_compliance.update',
      'ufms.rules_config.read',
      'ufms.rules_config.update',
      'ufms.rbac_matrix.read',
      'ufms.connector_readiness.read',
      'ufms.uat_checklist.read',
      'ufms.uat_checklist.update',
      'ufms.deployment_handover.read',
      'ufms.report_package.read',
      'ufms.report_package.export',
      'ufms.version_control.read',
      'dashboard:read',
      'operations:read',
      'work_orders:read',
      'work_orders:create',
      'work_orders:assign',
      'work_orders:update',
      'work_orders:close',
      'audit_logs:read',
      'registry:read',
      'evidence:read',
      'evidence:upload',
    ],
    operator: [
      'ufms.dashboard.view',
      'ufms.alarm.view',
      'ufms.alarm.create',
      'ufms.alarm.acknowledge',
      'ufms.episode.view',
      'ufms.episode.create',
      'ufms.problem.view',
      'ufms.problem.create',
      'ufms.workorder.view',
      'ufms.workorder.create',
      'ufms.report.view',
      'ufms.inspection.view',
      'ufms.ai_ops.view',
      'ufms.ai.recommendation.view',
      'ufms.ai.rca.view',
      'ufms.ai.rca.run',
      'dashboard:read',
      'operations:read',
      'events:read',
      'events:acknowledge',
      'work_orders:read',
      'work_orders:create',
    ],
    technician: [
      'ufms.mobile.use',
      'ufms.workorder.view',
      'ufms.workorder.execute',
      'ufms.sparepart.view',
      'ufms.sparepart.use',
      'ufms.alarm.view',
      'ufms.inspection.view',
      'ufms.inspection.execute',
      'field:execute',
      'work_orders:read',
      'work_orders:update',
      'evidence:upload',
      'spare_parts:read',
    ],
    contractor: [
      'ufms.mobile.use',
      'ufms.workorder.view',
      'ufms.workorder.execute',
      'ufms.alarm.view',
      'field:execute',
      'work_orders:read',
      'work_orders:update',
      'evidence:upload',
    ],
    requester: [
      'ufms.requester.submit',
      'ufms.requester.confirm',
      'ufms.requester.reopen',
      'ufms.requester.feedback',
      'ufms.workorder.view',
      'portal:requester',
    ],
    auditor: [
      'ufms.dashboard.view',
      'ufms.report.view',
      'ufms.report.export',
      'ufms.audit.view',
      'ufms.ai_ops.view',
      'ufms.ai.recommendation.view',
      'ufms.ai.rca.view',
      'ufms.rfq.view',
      'ufms.rfq.export',
      'ufms.health.view',
      'ufms.health.export',
      'dashboard:read',
      'audit_logs:read',
      'reports:read',
      'rfq:read',
    ],
    viewer: [
      'ufms.dashboard.view',
      'ufms.alarm.view',
      'ufms.episode.view',
      'ufms.problem.view',
      'ufms.workorder.view',
      'ufms.asset.view',
      'ufms.report.view',
      'ufms.ai_ops.view',
      'ufms.ai.recommendation.view',
      'ufms.ai.rca.view',
      'dashboard:read',
      'operations:read',
      'work_orders:read',
      'alarms:read',
      'episodes:read',
      'problems:read',
    ],
    engineer: [
      'ufms.mobile.use',
      'ufms.workorder.view',
      'ufms.workorder.execute',
      'ufms.sparepart.view',
      'ufms.sparepart.use',
      'ufms.alarm.view',
      'ufms.inspection.view',
      'ufms.inspection.execute',
      'field:execute',
      'work_orders:read',
      'work_orders:update',
      'evidence:upload',
      'spare_parts:read',
    ],
  }
}

export const UFMS_TEST_USERS = [
  { userId: 'USR-001', username: 'superadmin', displayName: 'Super Admin', email: 'superadmin@ufms.local', password: 'superadmin123', roleCode: 'super_admin' },
  { userId: 'USR-002', username: 'admin', displayName: 'System Admin', email: 'admin@ufms.local', password: 'admin123', roleCode: 'admin' },
  { userId: 'USR-003', username: 'fmmanager', displayName: 'FM Manager', email: 'fmmanager@ufms.local', password: 'fmmanager123', roleCode: 'fm_manager' },
  { userId: 'USR-004', username: 'supervisor', displayName: 'Supervisor', email: 'supervisor@ufms.local', password: 'supervisor123', roleCode: 'supervisor' },
  { userId: 'USR-005', username: 'operator', displayName: 'Operator', email: 'operator@ufms.local', password: 'operator123', roleCode: 'operator' },
  { userId: 'USR-006', username: 'technician', displayName: 'Technician', email: 'technician@ufms.local', password: 'technician123', roleCode: 'technician' },
  { userId: 'USR-007', username: 'contractor', displayName: 'Contractor', email: 'contractor@ufms.local', password: 'contractor123', roleCode: 'contractor' },
  { userId: 'USR-008', username: 'requester', displayName: 'Requester', email: 'requester@ufms.local', password: 'requester123', roleCode: 'requester' },
  { userId: 'USR-009', username: 'auditor', displayName: 'Auditor', email: 'auditor@ufms.local', password: 'auditor123', roleCode: 'auditor' },
  { userId: 'USR-010', username: 'viewer', displayName: 'Viewer', email: 'viewer@ufms.local', password: 'viewer123', roleCode: 'viewer' },
  { userId: 'USR-011', username: 'engineer', displayName: 'Field Engineer', email: 'engineer@ufms.local', password: 'engineer123', roleCode: 'engineer' },
] as const
