'use strict'

const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcrypt')

const prisma = new PrismaClient()
const BCRYPT_ROUNDS = 10;
const SEED_NOW = new Date('2026-06-02T10:00:00.000Z');
function parseMockTimestamp(value) {
    const normalized = value.replace(' ', 'T');
    return new Date(`${normalized}:00.000Z`);
}
function parseDueDate(value) {
    return new Date(`${value}T00:00:00.000Z`);
}
async function hashPassword(password) {
    return bcrypt.hash(password, BCRYPT_ROUNDS);
}
const PERMISSION_SEED = [
    { permissionId: 'PERM-001', permissionCode: 'registry:read', permissionName: 'Registry Read' },
    { permissionId: 'PERM-002', permissionCode: 'integration:read', permissionName: 'Integration Read' },
    { permissionId: 'PERM-003', permissionCode: 'operations:read', permissionName: 'Operations Read' },
    { permissionId: 'PERM-004', permissionCode: 'trust:read', permissionName: 'Trust Read' },
    { permissionId: 'PERM-005', permissionCode: 'decision:read', permissionName: 'Decision Read' },
    { permissionId: 'PERM-006', permissionCode: 'dashboard:read', permissionName: 'Dashboard Read' },
    { permissionId: 'PERM-007', permissionCode: 'operations:write', permissionName: 'Operations Write' },
    { permissionId: 'PERM-008', permissionCode: 'trust:append', permissionName: 'Trust Append' },
    { permissionId: 'PERM-009', permissionCode: 'evidence:upload', permissionName: 'Evidence Upload' },
    { permissionId: 'PERM-010', permissionCode: 'approval:request', permissionName: 'Approval Request' },
    { permissionId: 'PERM-011', permissionCode: 'approval:decide', permissionName: 'Approval Decide' },
    { permissionId: 'PERM-012', permissionCode: 'decision:submit', permissionName: 'Decision Submit' },
    { permissionId: 'PERM-013', permissionCode: 'decision:approve', permissionName: 'Decision Approve' },
    { permissionId: 'PERM-014', permissionCode: 'iam:user:read', permissionName: 'IAM User Read' },
    { permissionId: 'PERM-015', permissionCode: 'iam:user:create', permissionName: 'IAM User Create' },
    { permissionId: 'PERM-016', permissionCode: 'iam:user:update', permissionName: 'IAM User Update' },
    { permissionId: 'PERM-017', permissionCode: 'iam:user:disable', permissionName: 'IAM User Disable' },
    { permissionId: 'PERM-018', permissionCode: 'iam:user:reset-password', permissionName: 'IAM User Reset Password' },
    { permissionId: 'PERM-019', permissionCode: 'iam:role:assign', permissionName: 'IAM Role Assign' },
    {
        permissionId: 'PERM-020',
        permissionCode: 'import_batch:read',
        permissionName: 'Import Batch Governance Read',
    },
    {
        permissionId: 'PERM-021',
        permissionCode: 'import_batch:write',
        permissionName: 'Import Batch Governance Write',
    },
    {
        permissionId: 'PERM-022',
        permissionCode: 'fault_source:read',
        permissionName: 'Fault Source Governance Read',
    },
    {
        permissionId: 'PERM-023',
        permissionCode: 'fault_source:write',
        permissionName: 'Fault Source Governance Write',
    },
    {
        permissionId: 'PERM-024',
        permissionCode: 'data_quality:read',
        permissionName: 'Data Quality Dashboard Read',
    },
    {
        permissionId: 'PERM-025',
        permissionCode: 'data_lineage:read',
        permissionName: 'Data Lineage Lite Read',
    },
    {
        permissionId: 'PERM-026',
        permissionCode: 'pilot_activity:read',
        permissionName: 'Pilot Activity & Access Audit Read',
    },
    {
        permissionId: 'PERM-027',
        permissionCode: 'integration_config:read',
        permissionName: 'Integration Configuration Read',
    },
    {
        permissionId: 'PERM-028',
        permissionCode: 'integration_config:write',
        permissionName: 'Integration Configuration Write',
    },
];
const ROLE_PERMISSION_CODES = {
    admin: PERMISSION_SEED.map((p) => p.permissionCode),
    supervisor: [
        'registry:read',
        'integration:read',
        'operations:read',
        'trust:read',
        'decision:read',
        'dashboard:read',
        'operations:write',
        'trust:append',
        'evidence:upload',
        'approval:request',
        'approval:decide',
        'decision:submit',
        'decision:approve',
        'import_batch:read',
        'import_batch:write',
        'fault_source:read',
        'fault_source:write',
        'data_quality:read',
        'data_lineage:read',
        'pilot_activity:read',
    ],
    operator: [
        'registry:read',
        'integration:read',
        'operations:read',
        'dashboard:read',
        'operations:write',
        'trust:append',
        'evidence:upload',
        'approval:request',
        'decision:submit',
    ],
    viewer: [
        'registry:read',
        'integration:read',
        'operations:read',
        'trust:read',
        'decision:read',
        'dashboard:read',
    ],
};
async function main() {
    await prisma.rolePermission.deleteMany();
    await prisma.userRole.deleteMany();
    await prisma.user.deleteMany();
    await prisma.role.deleteMany();
    await prisma.permission.deleteMany();
    await prisma.decisionEvidence.deleteMany();
    await prisma.decision.deleteMany();
    await prisma.approval.deleteMany();
    await prisma.evidence.deleteMany();
    await prisma.auditLog.deleteMany();
    await prisma.timeline.deleteMany();
    await prisma.workOrder.deleteMany();
    await prisma.importBatchItem.deleteMany();
    await prisma.importBatch.deleteMany();
    await prisma.event.deleteMany();
    await prisma.incident.deleteMany();
    await prisma.integrationValueMapping.deleteMany();
    await prisma.integrationFieldMapping.deleteMany();
    await prisma.integrationProfile.deleteMany();
    await prisma.faultSource.deleteMany();
    await prisma.connector.deleteMany();
    await prisma.externalSystem.deleteMany();
    await prisma.adapter.deleteMany();
    await prisma.point.deleteMany();
    await prisma.device.deleteMany();
    await prisma.asset.deleteMany();
    await prisma.site.deleteMany();
    await prisma.site.createMany({
        data: [
            {
                siteId: 'SITE-001',
                siteCode: 'SG-DC',
                siteName: 'Singapore DC',
                country: 'Singapore',
                city: 'Singapore',
                siteType: 'data_center',
                status: 'active',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                siteId: 'SITE-002',
                siteCode: 'JUR-PLANT',
                siteName: 'Jurong Plant',
                country: 'Singapore',
                city: 'Jurong',
                siteType: 'industrial',
                status: 'active',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                siteId: 'SITE-003',
                siteCode: 'CHG-FAC',
                siteName: 'Changi Facility',
                country: 'Singapore',
                city: 'Changi',
                siteType: 'campus',
                status: 'active',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.asset.createMany({
        data: [
            {
                assetId: 'AST-001',
                siteId: 'SITE-001',
                parentAssetId: null,
                assetCode: 'SG-DC-BLD',
                assetName: 'Singapore DC Building',
                assetType: 'building',
                status: 'active',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                assetId: 'AST-002',
                siteId: 'SITE-001',
                parentAssetId: 'AST-001',
                assetCode: 'L1',
                assetName: 'Level 1',
                assetType: 'floor',
                status: 'active',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                assetId: 'AST-003',
                siteId: 'SITE-001',
                parentAssetId: 'AST-002',
                assetCode: 'UPS-RM',
                assetName: 'UPS Room',
                assetType: 'room',
                status: 'active',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                assetId: 'AST-004',
                siteId: 'SITE-001',
                parentAssetId: 'AST-003',
                assetCode: 'UPS-01',
                assetName: 'UPS-01',
                assetType: 'equipment',
                status: 'active',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.device.createMany({
        data: [
            {
                deviceId: 'DEV-001',
                siteId: 'SITE-001',
                assetId: 'AST-004',
                deviceCode: 'UPS-CTRL',
                deviceName: 'UPS Controller',
                deviceType: 'ups',
                status: 'online',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                deviceId: 'DEV-002',
                siteId: 'SITE-001',
                assetId: 'AST-004',
                deviceCode: 'CRAC-CTRL',
                deviceName: 'CRAC Controller',
                deviceType: 'crac',
                status: 'warning',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                deviceId: 'DEV-003',
                siteId: 'SITE-003',
                assetId: 'AST-004',
                deviceCode: 'PLC-CTRL',
                deviceName: 'PLC Controller',
                deviceType: 'plc',
                status: 'online',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.point.createMany({
        data: [
            {
                pointId: 'PT-001',
                deviceId: 'DEV-001',
                assetId: 'AST-004',
                pointCode: 'UPS.BATT.VOLT',
                pointName: 'Battery Voltage',
                pointType: 'analog',
                unit: 'V',
                value: 48.2,
                quality: 'good',
                timestamp: parseMockTimestamp('2026-06-02 10:15'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                pointId: 'PT-002',
                deviceId: 'DEV-001',
                assetId: 'AST-004',
                pointCode: 'UPS.BATT.AMP',
                pointName: 'Battery Current',
                pointType: 'analog',
                unit: 'A',
                value: 12.5,
                quality: 'good',
                timestamp: parseMockTimestamp('2026-06-02 10:15'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                pointId: 'PT-003',
                deviceId: 'DEV-001',
                assetId: 'AST-004',
                pointCode: 'UPS.BATT.TEMP',
                pointName: 'Battery Temperature',
                pointType: 'analog',
                unit: '°C',
                value: 32.1,
                quality: 'warning',
                timestamp: parseMockTimestamp('2026-06-02 10:16'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.adapter.createMany({
        data: [
            {
                adapterId: 'ADP-001',
                adapterCode: 'BACNET_ADAPTER',
                adapterName: 'BACnet Adapter',
                protocol: 'bacnet',
                version: '1.0',
                status: 'active',
                description: 'Generic BACnet adapter for BMS integration',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                adapterId: 'ADP-002',
                adapterCode: 'MODBUS_TCP_ADAPTER',
                adapterName: 'Modbus TCP Adapter',
                protocol: 'modbus',
                version: '1.0',
                status: 'active',
                description: 'Generic Modbus TCP adapter for PLC integration',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                adapterId: 'ADP-003',
                adapterCode: 'MQTT_ADAPTER',
                adapterName: 'MQTT Adapter',
                protocol: 'mqtt',
                version: '1.0',
                status: 'active',
                description: 'Generic MQTT adapter for IoT gateway integration',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                adapterId: 'ADP-004',
                adapterCode: 'REST_API_ADAPTER',
                adapterName: 'REST API Adapter',
                protocol: 'rest',
                version: '1.0',
                status: 'active',
                description: 'Generic REST API adapter for DCIM and external systems',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                adapterId: 'ADP-005',
                adapterCode: 'OPCUA_ADAPTER',
                adapterName: 'OPC-UA Adapter',
                protocol: 'opcua',
                version: '1.0',
                status: 'active',
                description: 'Generic OPC-UA adapter for industrial integration',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.externalSystem.createMany({
        data: [
            {
                externalSystemId: 'SYS-001',
                systemCode: 'IBMS-AEGIS',
                systemName: 'AegisNexus IBMS',
                systemType: 'ibms',
                vendor: 'AegisNexus',
                siteId: 'SITE-001',
                status: 'active',
                description: 'Primary integrated building management system at Singapore DC.',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                externalSystemId: 'SYS-002',
                systemCode: 'BMS-GEN',
                systemName: 'Building BMS',
                systemType: 'bms',
                vendor: 'Generic',
                siteId: 'SITE-001',
                status: 'active',
                description: 'Building-level BMS for HVAC and electrical monitoring.',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                externalSystemId: 'SYS-003',
                systemCode: 'DCIM-GEN',
                systemName: 'Data Center DCIM',
                systemType: 'dcim',
                vendor: 'Generic',
                siteId: 'SITE-001',
                status: 'active',
                description: 'Data center infrastructure management platform.',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                externalSystemId: 'SYS-004',
                systemCode: 'PLC-NET',
                systemName: 'PLC Network',
                systemType: 'plc',
                vendor: 'Generic',
                siteId: 'SITE-003',
                status: 'active',
                description: 'PLC network at Changi Facility.',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                externalSystemId: 'SYS-005',
                systemCode: 'TENABLE-OT',
                systemName: 'Tenable OT Security',
                systemType: 'ot_security',
                vendor: 'Tenable',
                siteId: 'SITE-001',
                status: 'active',
                description: 'OT security monitoring platform (Tenable OT).',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.connector.createMany({
        data: [
            {
                connectorId: 'CON-001',
                connectorCode: 'BMS-CONN',
                connectorName: 'Building BMS Connector',
                adapterId: 'ADP-001',
                protocol: 'BACnet',
                externalSystemId: 'SYS-002',
                status: 'connected',
                siteId: 'SITE-001',
                lastPollTime: parseMockTimestamp('2026-06-02 10:15'),
                description: 'BACnet/IP ingest for building management system at Singapore DC.',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                connectorId: 'CON-002',
                connectorCode: 'DCIM-CONN',
                connectorName: 'Data Center DCIM Connector',
                adapterId: 'ADP-004',
                protocol: 'REST API',
                externalSystemId: 'SYS-003',
                status: 'connected',
                siteId: 'SITE-001',
                lastPollTime: parseMockTimestamp('2026-06-02 10:18'),
                description: 'REST API ingest for data center DCIM platform.',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                connectorId: 'CON-003',
                connectorCode: 'PLC-CONN',
                connectorName: 'PLC Network Connector',
                adapterId: 'ADP-002',
                protocol: 'Modbus TCP',
                externalSystemId: 'SYS-004',
                status: 'warning',
                siteId: 'SITE-003',
                lastPollTime: parseMockTimestamp('2026-06-02 10:20'),
                description: 'Modbus TCP ingest for PLC network at Changi Facility.',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                connectorId: 'CON-004',
                connectorCode: 'TENABLE-CONN',
                connectorName: 'Tenable OT Connector',
                adapterId: 'ADP-004',
                protocol: 'API',
                externalSystemId: 'SYS-005',
                status: 'connected',
                siteId: 'SITE-001',
                lastPollTime: parseMockTimestamp('2026-06-02 10:25'),
                description: 'API ingest for Tenable OT security platform.',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.faultSource.createMany({
        data: [
            {
                sourceId: 'SRC-001',
                sourceName: 'BMS Alarm Feed',
                protocol: 'BACnet',
                status: 'Connected',
                lastPollTime: parseMockTimestamp('2026-06-02 10:15'),
                connectorId: 'CON-001',
                externalSystemId: 'SYS-002',
                sourceType: 'BMS',
                sourceCategory: 'building_automation',
                systemDomain: 'Building Management',
                siteName: 'DC Hall A',
                location: 'Building A',
                ownerTeam: 'BMS Operations',
                governanceStatus: 'ACTIVE',
                trustLevel: 'HIGH',
                dataCriticality: 'high',
                validationRequired: true,
                importAllowed: true,
                eventCreationAllowed: true,
                notes: 'Primary BMS alarm feed for hosted demo.',
                lastSeenAt: parseMockTimestamp('2026-06-02 10:15'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                sourceId: 'SRC-002',
                sourceName: 'CSV Pilot Import Source',
                protocol: 'CSV',
                status: 'Connected',
                lastPollTime: parseMockTimestamp('2026-06-02 10:18'),
                connectorId: 'CON-002',
                externalSystemId: 'SYS-003',
                sourceType: 'CSV_IMPORT',
                sourceCategory: 'csv_import',
                systemDomain: 'Operations',
                siteName: 'DC Hall A',
                location: 'Operations',
                ownerTeam: 'Operations',
                governanceStatus: 'ACTIVE',
                trustLevel: 'MEDIUM',
                dataCriticality: 'medium',
                validationRequired: true,
                importAllowed: true,
                eventCreationAllowed: true,
                notes: 'Governed CSV pilot import source (use in CSV faultSourceId).',
                lastSeenAt: parseMockTimestamp('2026-06-02 10:18'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                sourceId: 'SRC-003',
                sourceName: 'Manual Operator Entry',
                protocol: 'Manual',
                status: 'Connected',
                lastPollTime: parseMockTimestamp('2026-06-02 10:20'),
                connectorId: 'CON-003',
                externalSystemId: 'SYS-004',
                sourceType: 'MANUAL',
                sourceCategory: 'manual_entry',
                systemDomain: 'Facility Operations',
                siteName: 'DC Hall A',
                location: 'Control Room',
                ownerTeam: 'Operations',
                governanceStatus: 'ACTIVE',
                trustLevel: 'MEDIUM',
                dataCriticality: 'medium',
                validationRequired: false,
                importAllowed: false,
                eventCreationAllowed: true,
                notes: 'Operator manual fault observations.',
                lastSeenAt: parseMockTimestamp('2026-06-02 10:20'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                sourceId: 'SRC-004',
                sourceName: 'Legacy Chiller Fault Feed',
                protocol: 'SCADA',
                status: 'Warning',
                lastPollTime: parseMockTimestamp('2026-06-02 10:25'),
                connectorId: 'CON-004',
                externalSystemId: 'SYS-005',
                sourceType: 'SCADA',
                sourceCategory: 'hvac',
                systemDomain: 'Mechanical / HVAC',
                siteName: 'DC Hall A',
                location: 'Plant Room',
                ownerTeam: 'Mechanical',
                governanceStatus: 'DEGRADED',
                trustLevel: 'LOW',
                dataCriticality: 'high',
                validationRequired: true,
                importAllowed: true,
                eventCreationAllowed: true,
                notes: 'Legacy chiller feed — degraded reliability.',
                lastSeenAt: parseMockTimestamp('2026-06-02 10:25'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.integrationProfile.create({
        data: {
            profileId: 'PROFILE-001',
            profileCode: 'PROFILE-001',
            profileName: 'BMS Alarm Feed Mapping',
            description: 'Maps BMS alarm CSV columns to UFMS event fields for pilot imports.',
            sourceSystemName: 'Building Management System',
            sourceSystemType: 'BMS',
            inputMode: 'CSV_UPLOAD',
            linkedFaultSourceId: 'SRC-001',
            siteName: 'DC Hall A',
            systemDomain: 'Building Management',
            status: 'ACTIVE',
            ownerTeam: 'BMS Operations',
            unknownSeverityHandling: 'USE_DEFAULT',
            unknownStatusHandling: 'USE_DEFAULT',
            defaultSeverity: 'minor',
            defaultStatus: 'new',
            notes: 'Demo integration profile for B27 no-code mapping.',
            lastTestedAt: SEED_NOW,
            createdBy: 'seed-admin',
            createdAt: SEED_NOW,
            updatedAt: SEED_NOW,
            fieldMappings: {
                create: [
                    { mappingId: 'IFM-0001', externalFieldName: 'AlarmID', ufmsFieldName: 'externalEventId', isRequired: false, sortOrder: 0 },
                    { mappingId: 'IFM-0002', externalFieldName: 'AlarmText', ufmsFieldName: 'title', isRequired: true, sortOrder: 1 },
                    { mappingId: 'IFM-0003', externalFieldName: 'Priority', ufmsFieldName: 'severity', isRequired: true, defaultValue: 'minor', sortOrder: 2 },
                    { mappingId: 'IFM-0004', externalFieldName: 'AlarmTime', ufmsFieldName: 'occurredAt', isRequired: true, sortOrder: 3 },
                    { mappingId: 'IFM-0005', externalFieldName: 'EquipmentName', ufmsFieldName: 'assetName', isRequired: false, sortOrder: 4 },
                    { mappingId: 'IFM-0006', externalFieldName: 'CurrentStatus', ufmsFieldName: 'status', isRequired: false, defaultValue: 'new', sortOrder: 5 },
                ],
            },
            valueMappings: {
                create: [
                    { mappingId: 'IVM-0001', mappingType: 'severity', externalValue: 'P1', ufmsValue: 'critical', sortOrder: 0 },
                    { mappingId: 'IVM-0002', mappingType: 'severity', externalValue: 'P2', ufmsValue: 'major', sortOrder: 1 },
                    { mappingId: 'IVM-0003', mappingType: 'severity', externalValue: 'P3', ufmsValue: 'minor', sortOrder: 2 },
                    { mappingId: 'IVM-0004', mappingType: 'severity', externalValue: 'Warning', ufmsValue: 'warning', sortOrder: 3 },
                    { mappingId: 'IVM-0005', mappingType: 'severity', externalValue: 'Info', ufmsValue: 'info', sortOrder: 4 },
                    { mappingId: 'IVM-0006', mappingType: 'status', externalValue: 'Active', ufmsValue: 'new', sortOrder: 0 },
                    { mappingId: 'IVM-0007', mappingType: 'status', externalValue: 'Acknowledged', ufmsValue: 'acknowledged', sortOrder: 1 },
                    { mappingId: 'IVM-0008', mappingType: 'status', externalValue: 'Cleared', ufmsValue: 'resolved', sortOrder: 2 },
                ],
            },
        },
    });
    await prisma.incident.createMany({
        data: [
            {
                incidentId: 'INC-001',
                title: 'UPS Battery Incident',
                priority: 'P1',
                status: 'Investigating',
                severity: 'critical',
                category: 'equipment_fault',
                assignedTo: 'Leon',
                assetLabel: 'UPS-01',
                createdAt: parseMockTimestamp('2026-06-02 10:20'),
                updatedAt: SEED_NOW,
            },
            {
                incidentId: 'INC-002',
                title: 'High Temperature Incident',
                priority: 'P2',
                status: 'Assigned',
                severity: 'major',
                category: 'environmental_fault',
                assignedTo: 'Engineer A',
                assetLabel: 'CRAC-02',
                createdAt: parseMockTimestamp('2026-06-02 10:30'),
                updatedAt: SEED_NOW,
            },
            {
                incidentId: 'INC-003',
                title: 'PLC Communication Incident',
                priority: 'P3',
                status: 'Open',
                severity: 'minor',
                category: 'communication_fault',
                assignedTo: 'Engineer B',
                assetLabel: 'PLC-01',
                createdAt: parseMockTimestamp('2026-06-02 10:40'),
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.event.createMany({
        data: [
            {
                eventId: 'EVT-001',
                sourceId: 'SRC-004',
                sourceLabel: 'Legacy Chiller Fault Feed',
                severity: 'critical',
                category: 'equipment_fault',
                assetLabel: 'UPS-01',
                title: 'UPS Battery Alarm',
                status: 'New',
                occurredTime: parseMockTimestamp('2026-06-02 10:15'),
                incidentId: 'INC-001',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                eventId: 'EVT-002',
                sourceId: 'SRC-002',
                sourceLabel: 'CSV Pilot Import Source',
                severity: 'major',
                category: 'environmental_fault',
                assetLabel: 'CRAC-02',
                title: 'High Temperature Alarm',
                status: 'Active',
                occurredTime: parseMockTimestamp('2026-06-02 10:22'),
                incidentId: 'INC-002',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                eventId: 'EVT-003',
                sourceId: 'SRC-001',
                sourceLabel: 'BMS Alarm Feed',
                severity: 'minor',
                category: 'communication_fault',
                assetLabel: 'PLC-01',
                title: 'Communication Loss',
                status: 'Promoted',
                occurredTime: parseMockTimestamp('2026-06-02 10:31'),
                incidentId: 'INC-003',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.workOrder.createMany({
        data: [
            {
                workOrderId: 'WO-001',
                incidentId: 'INC-001',
                title: 'UPS Battery Replacement',
                assetId: 'AST-004',
                assetLabel: 'UPS-01',
                assignedTo: 'Leon',
                priority: 'P1',
                status: 'In Progress',
                dueDate: parseDueDate('2026-06-03'),
                createdAt: new Date('2026-06-02T10:25:00.000Z'),
                updatedAt: SEED_NOW,
            },
            {
                workOrderId: 'WO-002',
                incidentId: 'INC-002',
                title: 'CRAC High Temperature Investigation',
                assetId: 'AST-004',
                assetLabel: 'CRAC-02',
                assignedTo: 'Engineer A',
                priority: 'P2',
                status: 'Assigned',
                dueDate: parseDueDate('2026-06-04'),
                createdAt: new Date('2026-06-02T10:35:00.000Z'),
                updatedAt: SEED_NOW,
            },
            {
                workOrderId: 'WO-003',
                incidentId: 'INC-003',
                title: 'PLC Communication Recovery',
                assetId: 'AST-004',
                assetLabel: 'PLC-01',
                assignedTo: 'Engineer B',
                priority: 'P3',
                status: 'Open',
                dueDate: parseDueDate('2026-06-05'),
                createdAt: new Date('2026-06-02T10:45:00.000Z'),
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.timeline.createMany({
        data: [
            {
                timelineId: 'TL-001',
                entityType: 'event',
                entityId: 'EVT-001',
                action: 'created',
                message: 'UPS Battery Alarm received',
                actor: 'system',
                timestamp: parseMockTimestamp('2026-06-02 10:15'),
                source: 'system',
                syncStatus: 'synced',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                timelineId: 'TL-002',
                entityType: 'event',
                entityId: 'EVT-001',
                action: 'promoted',
                message: 'Event promoted to Incident INC-001',
                actor: 'Leon',
                timestamp: parseMockTimestamp('2026-06-02 10:20'),
                source: 'local',
                syncStatus: 'synced',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                timelineId: 'TL-003',
                entityType: 'incident',
                entityId: 'INC-001',
                action: 'investigating',
                message: 'Incident investigation started',
                actor: 'Leon',
                timestamp: parseMockTimestamp('2026-06-02 10:22'),
                source: 'local',
                syncStatus: 'synced',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                timelineId: 'TL-004',
                entityType: 'work_order',
                entityId: 'WO-001',
                action: 'work_order_created',
                message: 'Work Order created for UPS-01',
                actor: 'Leon',
                timestamp: parseMockTimestamp('2026-06-02 10:25'),
                source: 'local',
                syncStatus: 'synced',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                timelineId: 'TL-005',
                entityType: 'work_order',
                entityId: 'WO-001',
                action: 'in_progress',
                message: 'Technician started work',
                actor: 'Leon',
                timestamp: parseMockTimestamp('2026-06-02 10:40'),
                source: 'local',
                syncStatus: 'synced',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.auditLog.createMany({
        data: [
            {
                auditId: 'AUD-001',
                entityType: 'incident',
                entityId: 'INC-001',
                action: 'status_changed',
                oldValue: { status: 'Assigned' },
                newValue: { status: 'Investigating' },
                actor: 'Leon',
                timestamp: parseMockTimestamp('2026-06-02 10:21'),
                hash: 'a3f5c8e91b2d4f6078e9c1a2b3d4e5f6789012345678901234567890abcd',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                auditId: 'AUD-002',
                entityType: 'work_order',
                entityId: 'WO-001',
                action: 'assigned',
                oldValue: { assignedTo: null },
                newValue: { assignedTo: 'Leon' },
                actor: 'Supervisor',
                timestamp: parseMockTimestamp('2026-06-02 10:24'),
                hash: 'b4e6d9f02c3e5a7189f0d2b3c4d5e6f7890123456789012345678901bcde',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                auditId: 'AUD-003',
                entityType: 'work_order',
                entityId: 'WO-001',
                action: 'status_changed',
                oldValue: { status: 'Assigned' },
                newValue: { status: 'In Progress' },
                actor: 'Leon',
                timestamp: parseMockTimestamp('2026-06-02 10:26'),
                hash: 'c5f7e0a13d4f6b8290a1e3c4d5e6f7a8901234567890123456789012cdef',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.evidence.createMany({
        data: [
            {
                evidenceId: 'EVD-001',
                entityType: 'incident',
                entityId: 'INC-001',
                fileName: 'ups-battery-inspection.pdf',
                fileHash: 'd6e8f1b24e5a7c9301b2d4e5f6a7b8c9012345678901234567890def1',
                storagePath: 'evidence/EVD-001/ups-battery-inspection.pdf',
                uploadedBy: 'Leon',
                uploadedAt: parseMockTimestamp('2026-06-02 10:23'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                evidenceId: 'EVD-002',
                entityType: 'work_order',
                entityId: 'WO-001',
                fileName: 'wo-001-completion-photo.jpg',
                fileHash: 'e7f9a2c35f6b8d0412c3e4f5a6b7c8d01234567890123456789012ef12',
                storagePath: 'evidence/EVD-002/wo-001-completion-photo.jpg',
                uploadedBy: 'Leon',
                uploadedAt: parseMockTimestamp('2026-06-02 10:35'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.approval.createMany({
        data: [
            {
                approvalId: 'APR-001',
                entityType: 'incident',
                entityId: 'INC-001',
                approvalType: 'incident_closure',
                status: 'pending',
                requestedBy: 'Leon',
                approvedBy: null,
                requestedAt: parseMockTimestamp('2026-06-02 11:00'),
                approvedAt: null,
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                approvalId: 'APR-002',
                entityType: 'work_order',
                entityId: 'WO-001',
                approvalType: 'work_order_completion',
                status: 'approved',
                requestedBy: 'Leon',
                approvedBy: 'Supervisor',
                requestedAt: parseMockTimestamp('2026-06-02 10:30'),
                approvedAt: parseMockTimestamp('2026-06-02 10:45'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.decision.createMany({
        data: [
            {
                decisionId: 'DEC-001',
                incidentId: 'INC-001',
                workOrderId: 'WO-001',
                parentDecisionId: null,
                decisionType: 'root_cause_analysis',
                decisionStatus: 'approved',
                decisionSummary: 'UPS battery degradation confirmed',
                recommendedAction: 'Replace UPS battery module',
                approvedAction: 'Replace UPS battery module',
                decisionBy: 'Leon',
                approvedBy: 'Supervisor',
                decisionTime: parseMockTimestamp('2026-06-02 10:28'),
                decisionHash: 'f8a1b2c3d4e5f60718293a4b5c6d7e8f9012345678901234567890abcd',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                decisionId: 'DEC-002',
                incidentId: 'INC-002',
                workOrderId: 'WO-002',
                parentDecisionId: null,
                decisionType: 'maintenance_decision',
                decisionStatus: 'submitted',
                decisionSummary: 'CRAC temperature abnormal condition requires investigation',
                recommendedAction: 'Inspect CRAC cooling loop',
                approvedAction: null,
                decisionBy: 'Engineer A',
                approvedBy: null,
                decisionTime: parseMockTimestamp('2026-06-02 10:32'),
                decisionHash: 'a9b2c3d4e5f61829304b5c6d7e8f9a0123456789012345678901bcde',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.decisionEvidence.createMany({
        data: [
            {
                decisionEvidenceId: 'DEC-EVD-001',
                decisionId: 'DEC-001',
                evidenceId: 'EVD-001',
                linkType: 'supporting_evidence',
                linkedBy: 'Leon',
                linkedAt: parseMockTimestamp('2026-06-02 10:29'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                decisionEvidenceId: 'DEC-EVD-002',
                decisionId: 'DEC-001',
                evidenceId: 'EVD-002',
                linkType: 'work_order_evidence',
                linkedBy: 'Leon',
                linkedAt: parseMockTimestamp('2026-06-02 10:36'),
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.permission.createMany({
        data: PERMISSION_SEED.map((p) => ({
            ...p,
            description: `UFMS permission ${p.permissionCode}`,
            createdAt: SEED_NOW,
            updatedAt: SEED_NOW,
        })),
    });
    await prisma.role.createMany({
        data: [
            {
                roleId: 'ROLE-001',
                roleCode: 'admin',
                roleName: 'Administrator',
                description: 'Full configuration and all permissions',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                roleId: 'ROLE-002',
                roleCode: 'supervisor',
                roleName: 'Supervisor',
                description: 'Approve decisions and approvals; audit read',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                roleId: 'ROLE-003',
                roleCode: 'operator',
                roleName: 'Operator',
                description: 'Day-to-day operations and decision submit',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                roleId: 'ROLE-004',
                roleCode: 'viewer',
                roleName: 'Viewer',
                description: 'Read-only access across modules',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    const [adminHash, supervisorHash, operatorHash, viewerHash] = await Promise.all([
        hashPassword('admin123'),
        hashPassword('supervisor123'),
        hashPassword('operator123'),
        hashPassword('viewer123'),
    ]);
    await prisma.user.createMany({
        data: [
            {
                userId: 'USR-001',
                username: 'admin',
                displayName: 'System Admin',
                email: 'admin@ufms.local',
                passwordHash: adminHash,
                status: 'active',
                forcePasswordChange: false,
                failedLoginCount: 0,
                lastLoginAt: null,
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                userId: 'USR-002',
                username: 'supervisor',
                displayName: 'Supervisor',
                email: 'supervisor@ufms.local',
                passwordHash: supervisorHash,
                status: 'active',
                forcePasswordChange: false,
                failedLoginCount: 0,
                lastLoginAt: null,
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                userId: 'USR-003',
                username: 'operator',
                displayName: 'Leon',
                email: 'operator@ufms.local',
                passwordHash: operatorHash,
                status: 'active',
                forcePasswordChange: false,
                failedLoginCount: 0,
                lastLoginAt: null,
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                userId: 'USR-004',
                username: 'viewer',
                displayName: 'Viewer',
                email: 'viewer@ufms.local',
                passwordHash: viewerHash,
                status: 'active',
                forcePasswordChange: false,
                failedLoginCount: 0,
                lastLoginAt: null,
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    await prisma.userRole.createMany({
        data: [
            {
                userRoleId: 'UR-001',
                userId: 'USR-001',
                roleId: 'ROLE-001',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                userRoleId: 'UR-002',
                userId: 'USR-002',
                roleId: 'ROLE-002',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                userRoleId: 'UR-003',
                userId: 'USR-003',
                roleId: 'ROLE-003',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
            {
                userRoleId: 'UR-004',
                userId: 'USR-004',
                roleId: 'ROLE-004',
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            },
        ],
    });
    const permissionByCode = new Map(PERMISSION_SEED.map((p) => [p.permissionCode, p.permissionId]));
    const roleByCode = {
        admin: 'ROLE-001',
        supervisor: 'ROLE-002',
        operator: 'ROLE-003',
        viewer: 'ROLE-004',
    };
    let rolePermissionIndex = 1;
    const rolePermissionRows = [];
    for (const [roleCode, codes] of Object.entries(ROLE_PERMISSION_CODES)) {
        for (const code of codes) {
            const permissionId = permissionByCode.get(code);
            if (!permissionId) {
                throw new Error(`Missing permission seed for ${code}`);
            }
            rolePermissionRows.push({
                rolePermissionId: `RP-${String(rolePermissionIndex).padStart(3, '0')}`,
                roleId: roleByCode[roleCode],
                permissionId,
                createdAt: SEED_NOW,
                updatedAt: SEED_NOW,
            });
            rolePermissionIndex += 1;
        }
    }
    await prisma.rolePermission.createMany({ data: rolePermissionRows });
    console.log(`Seed complete: registry (3 sites, 4 assets, 3 devices, 3 points) + integration (5 systems, 5 adapters, 4 connectors, 4 fault sources) + operations (3 events, 3 incidents, 3 work orders, 5 timeline) + trust (3 audit logs, 2 evidence, 2 approvals) + decision (2 decisions, 2 decision evidence links) + auth (4 users, 4 roles, ${PERMISSION_SEED.length} permissions, 4 user roles, ${rolePermissionRows.length} role permissions)`);
}
main()
    .catch((e) => {
    console.error(e);
    process.exit(1);
})
    .finally(async () => {
    await prisma.$disconnect();
});
