import {
  AlarmStatus,
  ConnectorStatus,
  EpisodeStatus,
  InspectionStatus,
  Prisma,
  PrismaClient,
  ProblemStatus,
  RfqCoverageStatus,
  SlaStatus,
  WorkOrderStatus,
} from '@prisma/client'

type SeedTimestampFn = (value: string) => Date

/**
 * UFMS Commercial V1.0 core foundation seed:
 * locations, extended assets, SLA/SOP, contractors, spare parts,
 * alarms → episode → problem → work order workflow chain, inspections, RFQ matrix.
 */
export async function seedCommercialFoundation(
  prisma: PrismaClient,
  seedNow: Date,
  parseTimestamp: SeedTimestampFn,
): Promise<void> {
  await prisma.location.createMany({
    data: [
      {
        locationId: 'LOC-001',
        siteId: 'SITE-001',
        parentLocationId: null,
        locationCode: 'DC-HALL-A',
        locationName: 'Data Hall A',
        locationType: 'hall',
        status: 'active',
        description: 'Primary white-space data hall, Singapore DC.',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        locationId: 'LOC-002',
        siteId: 'SITE-001',
        parentLocationId: 'LOC-001',
        locationCode: 'UPS-RM-L1',
        locationName: 'UPS Room L1',
        locationType: 'room',
        status: 'active',
        description: 'Level 1 UPS and battery room.',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        locationId: 'LOC-003',
        siteId: 'SITE-001',
        parentLocationId: 'LOC-001',
        locationCode: 'CHW-PLANT',
        locationName: 'Chilled Water Plant',
        locationType: 'plant',
        status: 'active',
        description: 'Chiller plant serving Data Hall A.',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        locationId: 'LOC-004',
        siteId: 'SITE-002',
        parentLocationId: null,
        locationCode: 'PROD-FLOOR',
        locationName: 'Production Floor',
        locationType: 'floor',
        status: 'active',
        description: 'Main production floor, Jurong Plant.',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        locationId: 'LOC-005',
        siteId: 'SITE-002',
        parentLocationId: 'LOC-004',
        locationCode: 'UTIL-BAY',
        locationName: 'Utilities Bay',
        locationType: 'zone',
        status: 'active',
        description: 'Compressed air and process utilities bay.',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
    ],
  })

  await prisma.asset.createMany({
    data: [
      {
        assetId: 'AST-005',
        siteId: 'SITE-001',
        locationId: 'LOC-003',
        parentAssetId: 'AST-001',
        assetCode: 'CHLR-01',
        assetName: 'Chiller Unit 01',
        assetType: 'chiller',
        status: 'active',
        criticality: 'high',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        assetId: 'AST-006',
        siteId: 'SITE-001',
        locationId: 'LOC-001',
        parentAssetId: 'AST-002',
        assetCode: 'CRAC-02',
        assetName: 'CRAC Unit 02',
        assetType: 'crac',
        status: 'active',
        criticality: 'high',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        assetId: 'AST-007',
        siteId: 'SITE-001',
        locationId: 'LOC-001',
        parentAssetId: 'AST-002',
        assetCode: 'PDU-A1',
        assetName: 'PDU Row A1',
        assetType: 'pdu',
        status: 'active',
        criticality: 'medium',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        assetId: 'AST-008',
        siteId: 'SITE-002',
        locationId: 'LOC-004',
        parentAssetId: null,
        assetCode: 'BLD-MAIN',
        assetName: 'Jurong Main Building',
        assetType: 'building',
        status: 'active',
        criticality: 'high',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        assetId: 'AST-009',
        siteId: 'SITE-002',
        locationId: 'LOC-005',
        parentAssetId: 'AST-008',
        assetCode: 'AIR-COMP-01',
        assetName: 'Air Compressor 01',
        assetType: 'compressor',
        status: 'active',
        criticality: 'medium',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        assetId: 'AST-010',
        siteId: 'SITE-002',
        locationId: 'LOC-005',
        parentAssetId: 'AST-008',
        assetCode: 'PUMP-03',
        assetName: 'Process Pump 03',
        assetType: 'pump',
        status: 'active',
        criticality: 'medium',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
    ],
  })

  await prisma.asset.updateMany({
    where: { assetId: { in: ['AST-003', 'AST-004'] } },
    data: { locationId: 'LOC-002', criticality: 'critical' },
  })

  await prisma.connector.updateMany({
    where: { connectorId: 'CON-001' },
    data: { status: ConnectorStatus.ONLINE },
  })
  await prisma.connector.updateMany({
    where: { connectorId: 'CON-002' },
    data: { status: ConnectorStatus.ONLINE },
  })
  await prisma.connector.updateMany({
    where: { connectorId: 'CON-003' },
    data: { status: ConnectorStatus.DEGRADED, lastErrorMessage: 'Modbus timeout on poll cycle 2026-06-02T10:20:00Z' },
  })
  await prisma.connector.updateMany({
    where: { connectorId: 'CON-004' },
    data: { status: ConnectorStatus.ONLINE },
  })

  await prisma.slaPolicy.createMany({
    data: [
      {
        slaPolicyId: 'SLA-001',
        siteId: 'SITE-001',
        policyCode: 'P1-DC-RESPONSE',
        policyName: 'P1 Critical — Data Center Response',
        priority: 'P1',
        responseTimeMinutes: 15,
        resolveTimeMinutes: 240,
        warningThresholdPercent: 80,
        status: 'active',
        description: 'Critical infrastructure faults in Singapore DC.',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        slaPolicyId: 'SLA-002',
        siteId: 'SITE-001',
        policyCode: 'P2-DC-RESPONSE',
        policyName: 'P2 Major — Data Center Response',
        priority: 'P2',
        responseTimeMinutes: 60,
        resolveTimeMinutes: 480,
        warningThresholdPercent: 80,
        status: 'active',
        description: 'Major equipment faults requiring same-shift resolution.',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        slaPolicyId: 'SLA-003',
        siteId: 'SITE-002',
        policyCode: 'P2-PLANT-RESPONSE',
        policyName: 'P2 Major — Industrial Plant Response',
        priority: 'P2',
        responseTimeMinutes: 120,
        resolveTimeMinutes: 720,
        warningThresholdPercent: 75,
        status: 'active',
        description: 'Production floor and utilities response targets.',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
    ],
  })

  await prisma.sopRule.createMany({
    data: [
      {
        sopRuleId: 'SOP-001',
        siteId: 'SITE-001',
        ruleCode: 'UPS-BATT-ALARM',
        ruleName: 'UPS Battery Alarm Response',
        triggerType: 'alarm',
        triggerSeverity: 'critical',
        triggerCategory: 'equipment_fault',
        steps: [
          { step: 1, action: 'Acknowledge alarm within 5 minutes', role: 'operator' },
          { step: 2, action: 'Verify battery voltage and temperature readings', role: 'engineer' },
          { step: 3, action: 'Create work order if degradation confirmed', role: 'supervisor' },
          { step: 4, action: 'Notify facility manager if SLA at risk', role: 'system' },
        ] as Prisma.InputJsonValue,
        status: 'active',
        description: 'Standard operating procedure for UPS battery alarms.',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        sopRuleId: 'SOP-002',
        siteId: 'SITE-001',
        ruleCode: 'CHLR-HIGH-TEMP',
        ruleName: 'Chiller High Temperature Escalation',
        triggerType: 'alarm',
        triggerSeverity: 'critical',
        triggerCategory: 'environmental_fault',
        steps: [
          { step: 1, action: 'Correlate chiller and CRAC alarms into episode', role: 'operator' },
          { step: 2, action: 'Inspect chilled water loop and setpoints', role: 'engineer' },
          { step: 3, action: 'Escalate to supervisor if temperature rising >2°C/15min', role: 'system' },
        ] as Prisma.InputJsonValue,
        status: 'active',
        description: 'Escalation playbook for chiller high-temperature events.',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
    ],
  })

  await prisma.requester.create({
    data: {
      requesterId: 'REQ-001',
      siteId: 'SITE-001',
      requesterCode: 'TENANT-DC-A',
      name: 'Data Hall A Tenant Lead',
      email: 'tenant.dca@customer.example.com',
      organization: 'Customer Operations — Hall A',
      phone: '+65-6000-1001',
      status: 'active',
      createdAt: seedNow,
      updatedAt: seedNow,
    },
  })

  await prisma.contractor.createMany({
    data: [
      {
        contractorId: 'CTR-001',
        siteId: 'SITE-001',
        contractorCode: 'MECH-SVC-SG',
        name: 'Singapore Mechanical Services Pte Ltd',
        contactEmail: 'dispatch@mechsvc.example.com',
        contactPhone: '+65-6000-2001',
        specialty: 'HVAC and chiller maintenance',
        status: 'active',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        contractorId: 'CTR-002',
        siteId: 'SITE-001',
        contractorCode: 'ELEC-UPS-SG',
        name: 'PowerGuard Electrical Contractors',
        contactEmail: 'jobs@powerguard.example.com',
        contactPhone: '+65-6000-2002',
        specialty: 'UPS and electrical systems',
        status: 'active',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
    ],
  })

  await prisma.sparePart.createMany({
    data: [
      {
        sparePartId: 'PART-001',
        siteId: 'SITE-001',
        assetId: 'AST-004',
        partCode: 'UPS-BATT-MOD-A',
        partName: 'UPS Battery Module Type A',
        quantityOnHand: 4,
        reorderLevel: 2,
        unitCost: 1250.0,
        status: 'active',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        sparePartId: 'PART-002',
        siteId: 'SITE-001',
        assetId: 'AST-005',
        partCode: 'CHLR-FILTER-KIT',
        partName: 'Chiller Filter Service Kit',
        quantityOnHand: 6,
        reorderLevel: 3,
        unitCost: 180.0,
        status: 'active',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        sparePartId: 'PART-003',
        siteId: 'SITE-002',
        assetId: 'AST-010',
        partCode: 'PUMP-SEAL-KIT',
        partName: 'Process Pump Mechanical Seal Kit',
        quantityOnHand: 2,
        reorderLevel: 1,
        unitCost: 95.0,
        status: 'active',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
    ],
  })

  await prisma.problem.create({
    data: {
      problemId: 'PRB-001',
      problemCode: 'PRB-UPS-DEGRAD',
      siteId: 'SITE-001',
      assetId: 'AST-004',
      locationId: 'LOC-002',
      title: 'Recurring UPS Battery Degradation — UPS-01',
      description:
        'Repeated battery voltage drop alarms on UPS-01 over 14 days. Root cause under investigation.',
      status: ProblemStatus.UNDER_INVESTIGATION,
      rootCause: 'Battery module end-of-life; replacement cycle exceeded manufacturer recommendation.',
      openedAt: parseTimestamp('2026-06-01 08:00'),
      createdById: 'USR-002',
      createdAt: seedNow,
      updatedAt: seedNow,
    },
  })

  await prisma.episode.create({
    data: {
      episodeId: 'EPI-001',
      episodeCode: 'EPI-2026-0602-UPS',
      siteId: 'SITE-001',
      locationId: 'LOC-002',
      problemId: 'PRB-001',
      title: 'UPS-01 Battery Fault Episode — June 2026',
      description:
        'Correlated UPS battery alarms and supporting CRAC temperature excursions in Data Hall A.',
      status: EpisodeStatus.LINKED_TO_PROBLEM,
      openedAt: parseTimestamp('2026-06-02 10:15'),
      createdById: 'USR-003',
      createdAt: seedNow,
      updatedAt: seedNow,
    },
  })

  await prisma.alarm.createMany({
    data: [
      {
        alarmId: 'ALM-001',
        alarmCode: 'ALM-UPS-BATT-001',
        eventId: 'EVT-001',
        episodeId: 'EPI-001',
        assetId: 'AST-004',
        locationId: 'LOC-002',
        connectorId: 'CON-001',
        title: 'UPS Battery Voltage Low',
        severity: 'critical',
        status: AlarmStatus.ACKNOWLEDGED,
        occurredAt: parseTimestamp('2026-06-02 10:15'),
        acknowledgedAt: parseTimestamp('2026-06-02 10:18'),
        createdById: 'USR-003',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        alarmId: 'ALM-002',
        alarmCode: 'ALM-CHLR-TEMP-001',
        eventId: 'EVT-004',
        episodeId: 'EPI-001',
        assetId: 'AST-005',
        locationId: 'LOC-003',
        connectorId: 'CON-001',
        title: 'Chiller Supply Temperature High',
        severity: 'critical',
        status: AlarmStatus.CORRELATED,
        occurredAt: parseTimestamp('2026-06-02 10:40'),
        createdById: 'USR-003',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        alarmId: 'ALM-003',
        alarmCode: 'ALM-CRAC-TEMP-001',
        eventId: 'EVT-002',
        assetId: 'AST-006',
        locationId: 'LOC-001',
        connectorId: 'CON-002',
        title: 'CRAC Return Air Temperature High',
        severity: 'major',
        status: AlarmStatus.NEW,
        occurredAt: parseTimestamp('2026-06-02 10:22'),
        createdAt: seedNow,
        updatedAt: seedNow,
      },
    ],
  })

  await prisma.event.updateMany({
    where: { eventId: { in: ['EVT-001', 'EVT-004', 'EVT-002'] } },
    data: { connectorId: 'CON-001', locationId: 'LOC-002' },
  })
  await prisma.event.update({
    where: { eventId: 'EVT-004' },
    data: { locationId: 'LOC-003', assetId: 'AST-005', connectorId: 'CON-001' },
  })
  await prisma.event.update({
    where: { eventId: 'EVT-002' },
    data: { locationId: 'LOC-001', assetId: 'AST-006', connectorId: 'CON-002' },
  })

  await prisma.workOrder.update({
    where: { workOrderId: 'WO-001' },
    data: {
      problemId: 'PRB-001',
      episodeId: 'EPI-001',
      locationId: 'LOC-002',
      slaPolicyId: 'SLA-001',
      slaStatus: SlaStatus.RUNNING,
      slaDueAt: parseTimestamp('2026-06-02 14:15'),
      requesterId: 'REQ-001',
      contractorId: 'CTR-002',
      status: WorkOrderStatus.IN_PROGRESS,
      requesterConfirmedAt: null,
      supervisorClosedAt: null,
      updatedAt: seedNow,
    },
  })

  await prisma.workOrderSparePart.create({
    data: {
      workOrderSparePartId: 'WOSP-001',
      workOrderId: 'WO-001',
      sparePartId: 'PART-001',
      quantityUsed: 1,
      issuedAt: parseTimestamp('2026-06-02 10:30'),
      issuedBy: 'USR-005',
      notes: 'Reserved battery module for UPS-01 replacement.',
      createdAt: seedNow,
      updatedAt: seedNow,
    },
  })

  await prisma.evidence.update({
    where: { evidenceId: 'EVD-002' },
    data: { workOrderId: 'WO-001' },
  })

  await prisma.inspectionPlan.create({
    data: {
      inspectionPlanId: 'INSP-PLAN-001',
      siteId: 'SITE-001',
      assetId: 'AST-004',
      locationId: 'LOC-002',
      planCode: 'UPS-MONTHLY',
      planName: 'UPS Monthly Preventive Inspection',
      frequency: 'monthly',
      nextScheduledAt: parseTimestamp('2026-07-01 09:00'),
      status: 'active',
      description: 'Monthly UPS battery and electrical inspection per ISO 55000 maintenance schedule.',
      createdAt: seedNow,
      updatedAt: seedNow,
      checklists: {
        create: [
          {
            checklistId: 'CHK-001',
            itemCode: 'BATT-VOLT',
            itemLabel: 'Battery string voltage within specification',
            itemType: 'boolean',
            sortOrder: 1,
            isRequired: true,
            createdAt: seedNow,
            updatedAt: seedNow,
          },
          {
            checklistId: 'CHK-002',
            itemCode: 'BATT-TEMP',
            itemLabel: 'Battery compartment temperature (°C)',
            itemType: 'numeric',
            sortOrder: 2,
            isRequired: true,
            createdAt: seedNow,
            updatedAt: seedNow,
          },
          {
            checklistId: 'CHK-003',
            itemCode: 'VISUAL',
            itemLabel: 'Visual inspection — leaks, corrosion, alarms clear',
            itemType: 'boolean',
            sortOrder: 3,
            isRequired: true,
            createdAt: seedNow,
            updatedAt: seedNow,
          },
        ],
      },
    },
  })

  await prisma.inspectionRecord.create({
    data: {
      inspectionRecordId: 'INSP-REC-001',
      inspectionPlanId: 'INSP-PLAN-001',
      assetId: 'AST-004',
      locationId: 'LOC-002',
      workOrderId: 'WO-001',
      recordCode: 'INSP-2026-06-UPS',
      status: InspectionStatus.IN_PROGRESS,
      scheduledAt: parseTimestamp('2026-06-02 11:00'),
      startedAt: parseTimestamp('2026-06-02 11:05'),
      performedBy: 'USR-005',
      results: {
        'BATT-VOLT': { value: false, notes: 'Voltage below threshold — matches active alarm' },
        'BATT-TEMP': { value: 34.2, unit: 'C' },
        VISUAL: { value: true, notes: 'No corrosion; alarm panel active' },
      } as Prisma.InputJsonValue,
      createdAt: seedNow,
      updatedAt: seedNow,
    },
  })

  const reportRangeFrom = parseTimestamp('2026-05-07T00:00:00.000Z')

  await prisma.aiRecommendation.createMany({
    data: [
      {
        recommendationId: 'AI-REC-SEED-001',
        sourceType: 'problem',
        sourceId: 'PRB-001',
        riskLevel: 'HIGH',
        suggestedAction: 'Complete RCA for chiller surge — verify condenser approach temperature during peak load.',
        confidence: 0.86,
        evidence: ['PRB-001', 'ALM-001', 'AST-001'] as Prisma.InputJsonValue,
        status: 'PENDING_REVIEW',
        provider: 'RULE_ENGINE',
        modelVersion: 'ufms-rules-v1',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        recommendationId: 'AI-REC-SEED-002',
        sourceType: 'alarm',
        sourceId: 'ALM-001',
        riskLevel: 'HIGH',
        suggestedAction: 'Acknowledge critical chiller discharge temperature alarm and link to episode EPI-001.',
        confidence: 0.91,
        evidence: ['ALM-001', 'EPI-001'] as Prisma.InputJsonValue,
        status: 'APPROVED',
        reviewer: 'fm_manager',
        reviewedAt: seedNow,
        provider: 'RULE_ENGINE',
        modelVersion: 'ufms-rules-v1',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        recommendationId: 'AI-REC-SEED-003',
        sourceType: 'work_order',
        sourceId: 'WO-001',
        riskLevel: 'MEDIUM',
        suggestedAction: 'Review SLA timing on WO-001 and confirm contractor response evidence is attached.',
        confidence: 0.74,
        evidence: ['WO-001'] as Prisma.InputJsonValue,
        status: 'PENDING_REVIEW',
        provider: 'RULE_ENGINE',
        modelVersion: 'ufms-rules-v1',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
    ],
    skipDuplicates: true,
  })

  await prisma.reportRun.createMany({
    data: [
      {
        runId: 'RPT-RUN-SEED-001',
        reportType: 'alarm-summary',
        reportName: 'Alarm Summary Report',
        siteId: 'SITE-001',
        timeRangeFrom: reportRangeFrom,
        timeRangeTo: seedNow,
        format: 'csv',
        status: 'completed',
        generatedBy: 'admin',
        generatedAt: seedNow,
        filters: { siteId: 'SITE-001', timeRange: '30d' } as Prisma.InputJsonValue,
      },
      {
        runId: 'RPT-RUN-SEED-002',
        reportType: 'work-order-summary',
        reportName: 'Work Order Summary Report',
        siteId: 'SITE-001',
        timeRangeFrom: reportRangeFrom,
        timeRangeTo: seedNow,
        format: 'preview',
        status: 'completed',
        generatedBy: 'fm_manager',
        generatedAt: seedNow,
        filters: { siteId: 'SITE-001', timeRange: '30d' } as Prisma.InputJsonValue,
      },
      {
        runId: 'RPT-RUN-SEED-003',
        reportType: 'daily-fault-summary',
        reportName: 'Daily Fault Summary',
        siteId: null,
        timeRangeFrom: reportRangeFrom,
        timeRangeTo: seedNow,
        format: 'html',
        status: 'completed',
        generatedBy: 'auditor',
        generatedAt: seedNow,
        filters: { timeRange: '7d' } as Prisma.InputJsonValue,
      },
      {
        runId: 'RPT-RUN-SEED-004',
        reportType: 'incident-summary',
        reportName: 'Incident Summary Report',
        siteId: 'SITE-002',
        timeRangeFrom: reportRangeFrom,
        timeRangeTo: seedNow,
        format: 'csv',
        status: 'completed',
        generatedBy: 'admin',
        generatedAt: seedNow,
        filters: { siteId: 'SITE-002', timeRange: '90d' } as Prisma.InputJsonValue,
      },
      {
        runId: 'RPT-RUN-SEED-005',
        reportType: 'rfq-compliance',
        reportName: 'RFQ Compliance',
        siteId: null,
        timeRangeFrom: reportRangeFrom,
        timeRangeTo: seedNow,
        format: 'csv',
        status: 'completed',
        generatedBy: 'admin',
        generatedAt: seedNow,
        filters: { timeRange: '30d' } as Prisma.InputJsonValue,
      },
    ],
    skipDuplicates: true,
  })

  await prisma.report.createMany({
    data: [
      {
        reportId: 'RPT-001',
        reportCode: 'INCIDENT-SUMMARY',
        reportName: 'Incident Summary Report',
        reportType: 'operational',
        moduleScope: 'operations',
        status: 'active',
        description: 'Weekly incident and work order summary for supervisors.',
        templateConfig: { groupBy: 'priority', includeSla: true } as Prisma.InputJsonValue,
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        reportId: 'RPT-002',
        reportCode: 'SLA-COMPLIANCE',
        reportName: 'SLA Compliance Report',
        reportType: 'compliance',
        moduleScope: 'sla',
        status: 'active',
        description: 'SLA breach and met-rate analysis by site and priority.',
        templateConfig: { metrics: ['breach_rate', 'mean_time_to_resolve'] } as Prisma.InputJsonValue,
        createdAt: seedNow,
        updatedAt: seedNow,
      },
    ],
  })

  await prisma.rfqComplianceItem.createMany({
    data: [
      {
        rfqItemId: 'RFQ-001',
        requirementCode: 'RFQ-OPS-DASHBOARD',
        requirementTitle: 'Operations Dashboard with real-time KPIs',
        ufmsModule: 'operations_dashboard',
        coverageStatus: RfqCoverageStatus.FULL,
        notes: 'Dashboard module with events, incidents, work orders, connector health.',
        sortOrder: 1,
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        rfqItemId: 'RFQ-002',
        requirementCode: 'RFQ-ALARM-CONSOLE',
        requirementTitle: 'Unified Alarm Console with correlation',
        ufmsModule: 'unified_alarm_console',
        coverageStatus: RfqCoverageStatus.PARTIAL,
        notes: 'Alarm data model and seed; dedicated console UI in next phase.',
        sortOrder: 2,
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        rfqItemId: 'RFQ-003',
        requirementCode: 'RFQ-SLA-ENGINE',
        requirementTitle: 'Configurable SLA policies and breach tracking',
        ufmsModule: 'work_orders_sla',
        coverageStatus: RfqCoverageStatus.CONFIGURABLE,
        notes: 'SLA policies seeded; runtime breach engine in next phase.',
        sortOrder: 3,
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        rfqItemId: 'RFQ-004',
        requirementCode: 'RFQ-OT-CYBER',
        requirementTitle: 'OT cyber correlation with Tenable OT',
        ufmsModule: 'ot_cyber_correlation',
        coverageStatus: RfqCoverageStatus.PLANNED_IN_V2,
        notes: 'Explicitly excluded from Commercial V1.0 scope.',
        sortOrder: 4,
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        rfqItemId: 'RFQ-005',
        requirementCode: 'RFQ-MOBILE-NATIVE',
        requirementTitle: 'Native iOS/Android field application',
        ufmsModule: 'mobile_field_execution',
        coverageStatus: RfqCoverageStatus.PLANNED_IN_V2,
        notes: 'PWA responsive field pages in V1.0; native apps V2.0.',
        sortOrder: 5,
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        rfqItemId: 'RFQ-006',
        requirementCode: 'RFQ-INTEGRATION-CENTER',
        requirementTitle: 'Self-service integration configuration',
        ufmsModule: 'integration_center',
        coverageStatus: RfqCoverageStatus.FULL,
        notes: 'Integration Center V1 with productized packages.',
        sortOrder: 6,
        createdAt: seedNow,
        updatedAt: seedNow,
      },
    ],
  })

  await prisma.notification.create({
    data: {
      notificationId: 'NTF-001',
      sopRuleId: 'SOP-001',
      entityType: 'alarm',
      entityId: 'ALM-001',
      channel: 'email',
      recipient: 'supervisor@ufms.local',
      subject: '[P1] UPS Battery Alarm — UPS-01',
      body: 'UPS battery voltage low alarm acknowledged. Work order WO-001 in progress. SLA timer running.',
      status: 'sent',
      sentAt: parseTimestamp('2026-06-02 10:20'),
      createdAt: seedNow,
      updatedAt: seedNow,
    },
  })

  await prisma.auditLog.createMany({
    data: [
      {
        auditId: 'AUD-COM-001',
        entityType: 'episode',
        entityId: 'EPI-001',
        module: 'operations',
        action: 'episode_created',
        newValue: { status: EpisodeStatus.OPEN, title: 'UPS-01 Battery Fault Episode — June 2026' },
        actor: 'operator',
        timestamp: parseTimestamp('2026-06-02 10:16'),
        hash: 'd1e2f3a4b5c6d7e8f9012345678901234567890abcdef1234567890abcdef12',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        auditId: 'AUD-COM-002',
        entityType: 'problem',
        entityId: 'PRB-001',
        module: 'operations',
        action: 'problem_status_changed',
        oldValue: { status: ProblemStatus.OPEN },
        newValue: { status: ProblemStatus.UNDER_INVESTIGATION },
        actor: 'supervisor',
        timestamp: parseTimestamp('2026-06-02 10:25'),
        hash: 'e2f3a4b5c6d7e8f9012345678901234567890abcdef1234567890abcdef1234',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
      {
        auditId: 'AUD-COM-003',
        entityType: 'work_order',
        entityId: 'WO-001',
        module: 'operations',
        action: 'sla_started',
        newValue: { slaPolicyId: 'SLA-001', slaStatus: SlaStatus.RUNNING },
        actor: 'system',
        timestamp: parseTimestamp('2026-06-02 10:25'),
        hash: 'f3a4b5c6d7e8f9012345678901234567890abcdef1234567890abcdef123456',
        createdAt: seedNow,
        updatedAt: seedNow,
      },
    ],
  })

  console.log(
    'Commercial foundation seed: 5 locations, 6 additional assets, 3 SLA policies, 2 SOP rules, 2 contractors, 3 spare parts, 3 alarms, 1 episode, 1 problem, WO-001 linked, 1 inspection plan, 6 RFQ items, 2 reports',
  )
}
