"""Enums for read-only Operations Console Packages."""
from __future__ import annotations

from enum import Enum

CONTRACT_VERSION = "read-only-operations-console-package.v1"


class PageType(str, Enum):
    OVERVIEW = "OVERVIEW"
    INTEGRATION_HEALTH = "INTEGRATION_HEALTH"
    ASSET_REVIEW = "ASSET_REVIEW"
    ALARM_EVENT_OPERATIONS = "ALARM_EVENT_OPERATIONS"
    FAULTCASE_CANDIDATES = "FAULTCASE_CANDIDATES"
    WORKORDER_INTENT_CANDIDATES = "WORKORDER_INTENT_CANDIDATES"
    EVIDENCE_INVESTIGATION = "EVIDENCE_INVESTIGATION"
    OPERATOR_REVIEW_QUEUE = "OPERATOR_REVIEW_QUEUE"
    RELEASE_GATE = "RELEASE_GATE"
    UNKNOWN = "UNKNOWN"


class ReadinessState(str, Enum):
    READY_FOR_READ_ONLY_CONSUMPTION = "READY_FOR_READ_ONLY_CONSUMPTION"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"
    RUNTIME_PENDING = "RUNTIME_PENDING"
    NOT_READY = "NOT_READY"


class CardType(str, Enum):
    SUMMARY = "SUMMARY"
    QUEUE = "QUEUE"
    REVIEW = "REVIEW"
    HEALTH = "HEALTH"
    EVIDENCE = "EVIDENCE"
    RELEASE_GATE = "RELEASE_GATE"
    WARNING = "WARNING"


class GateStatus(str, Enum):
    PASS = "PASS"
    PASS_WITH_WARNINGS = "PASS_WITH_WARNINGS"
    FAIL = "FAIL"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class Severity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
