"""Frozen status vocabulary for Device projection reconciliation."""
from enum import Enum

RECONCILIATION_AUTHORITY = "ONE-A5-P1-16A"
RECONCILIATION_VERSION = "1.0.0"
MAX_RECONCILIATION_BATCH_SIZE = 100
DEFAULT_CUTOVER_DECISION = "NOT_READY_FOR_WRITE_CUTOVER"


class Severity(str, Enum):
    BLOCKER = "BLOCKER"
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"
    REVIEW = "REVIEW"


class DimensionStatus(str, Enum):
    PASS = "PASS"
    PASS_WITH_WARNINGS = "PASS_WITH_WARNINGS"
    MISMATCH = "MISMATCH"
    MISSING = "MISSING"
    COLLISION = "COLLISION"
    PROHIBITED_EXCLUDED = "PROHIBITED_EXCLUDED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class CutoverDecision(str, Enum):
    READY_FOR_PROVIDER_FOUNDATION = "READY_FOR_PROVIDER_FOUNDATION"
    READY_FOR_READ_MIGRATION = "READY_FOR_READ_MIGRATION"
    NOT_READY_FOR_WRITE_CUTOVER = "NOT_READY_FOR_WRITE_CUTOVER"
    BLOCKED_BY_IDENTITY = "BLOCKED_BY_IDENTITY"
    BLOCKED_BY_SCOPE = "BLOCKED_BY_SCOPE"
    BLOCKED_BY_REQUIRED_FIELDS = "BLOCKED_BY_REQUIRED_FIELDS"
    BLOCKED_BY_RELATIONSHIPS = "BLOCKED_BY_RELATIONSHIPS"
    BLOCKED_BY_REVIEW = "BLOCKED_BY_REVIEW"
    BLOCKED_BY_NONDETERMINISM = "BLOCKED_BY_NONDETERMINISM"


class PointClassification(str, Enum):
    PROJECTED_POINT = "PROJECTED_POINT"
    CONFIGURATION_FIELD = "CONFIGURATION_FIELD"
    METADATA_FIELD = "METADATA_FIELD"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    EXCLUDED_PROHIBITED = "EXCLUDED_PROHIBITED"
