"""Frozen value definitions for the canonical Asset Graph foundation."""
from enum import Enum


class LifecycleStatus(str, Enum):
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    RETIRED = "RETIRED"


class OperationalStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    MAINTENANCE = "MAINTENANCE"


class PointAccessMode(str, Enum):
    READ_ONLY = "READ_ONLY"
    WRITE_CAPABLE = "WRITE_CAPABLE"
    COMMAND_ONLY = "COMMAND_ONLY"


class TagType(str, Enum):
    SOURCE_TAG_NAME = "SOURCE_TAG_NAME"
    CLASSIFICATION = "CLASSIFICATION"
    BUSINESS_LABEL = "BUSINESS_LABEL"
    LOCATION_LABEL = "LOCATION_LABEL"
    EXTERNAL_REFERENCE = "EXTERNAL_REFERENCE"


class RelationshipType(str, Enum):
    CONTAINS = "CONTAINS"
    LOCATED_IN = "LOCATED_IN"
    PART_OF = "PART_OF"
    CONNECTED_TO = "CONNECTED_TO"
    SERVES = "SERVES"
    MONITORS = "MONITORS"
    CONTROLS = "CONTROLS"
    HAS_POINT = "HAS_POINT"
    REPRESENTS_SOURCE_OBJECT = "REPRESENTS_SOURCE_OBJECT"


class OperationStatus(str, Enum):
    ACCEPTED = "ACCEPTED"
    DUPLICATE_IDENTICAL = "DUPLICATE_IDENTICAL"
    CONFLICT = "CONFLICT"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"


MAX_QUERY_LIMIT = 100
DEFAULT_QUERY_LIMIT = 50
MAX_IDENTIFIER_LENGTH = 512
ASSET_GRAPH_OWNER = "ONE Asset Graph"
IN_MEMORY_STATUS = "NON_PRODUCTION_IN_MEMORY_PROVIDER"
