import type {
  ConnectorCapabilityMatrixEntry,
  ConnectorCapabilityMatrixSnapshot,
} from './connector-capability-matrix-types.js';

const MATRIX: readonly ConnectorCapabilityMatrixEntry[] = [
  {
    protocolKey: 'file',
    displayName: 'File Import',
    category: 'file-import',
    direction: 'ingest-readonly',
    networkEnabled: false,
    supportsWriteback: false,
    syntheticFixtureOnly: true,
    realConnectivityEnabled: false,
    fixturePath: 'config/samples/file-import-sample.jsonl',
    configValidation: true,
    normalizationSupported: true,
    envelopeSupported: true,
    localBufferSupported: true,
    deliveryPreviewSupported: true,
    auditSupported: true,
    diagnosticsSupported: true,
    productionDependencyIncluded: false,
    productionDependencyName: 'none',
    productionEnablementGate: 'Introduce controlled import adapters with explicit path sandbox and security review.',
    readinessKey: 'UFMS_EDGE_C3_01_FILE_IMPORT_CONNECTOR_FOUNDATION_PASS',
    foundationStatus: 'foundation-ready',
  },
  {
    protocolKey: 'http',
    displayName: 'HTTP Polling',
    category: 'http-polling',
    direction: 'ingest-readonly',
    networkEnabled: false,
    supportsWriteback: false,
    syntheticFixtureOnly: true,
    realConnectivityEnabled: false,
    fixturePath: 'config/samples/http-polling-response.json',
    configValidation: true,
    normalizationSupported: true,
    envelopeSupported: true,
    localBufferSupported: true,
    deliveryPreviewSupported: true,
    auditSupported: true,
    diagnosticsSupported: true,
    productionDependencyIncluded: false,
    productionDependencyName: 'none',
    productionEnablementGate: 'Introduce allowlisted endpoint transport and outbound security gate before real HTTP enablement.',
    readinessKey: 'UFMS_EDGE_C3_02_HTTP_POLLING_CONNECTOR_FOUNDATION_PASS',
    foundationStatus: 'foundation-ready',
  },
  {
    protocolKey: 'snmp',
    displayName: 'SNMP Read-only',
    category: 'industrial-readonly',
    direction: 'ingest-readonly',
    networkEnabled: false,
    supportsWriteback: false,
    syntheticFixtureOnly: true,
    realConnectivityEnabled: false,
    fixturePath: 'config/samples/snmp-readonly-response.json',
    configValidation: true,
    normalizationSupported: true,
    envelopeSupported: true,
    localBufferSupported: true,
    deliveryPreviewSupported: true,
    auditSupported: true,
    diagnosticsSupported: true,
    productionDependencyIncluded: false,
    productionDependencyName: 'none',
    productionEnablementGate: 'Introduce audited SNMP transport with credential vault integration and SET prohibition guard.',
    readinessKey: 'UFMS_EDGE_C3_03_SNMP_READONLY_CONNECTOR_FOUNDATION_PASS',
    foundationStatus: 'foundation-ready',
  },
  {
    protocolKey: 'modbus',
    displayName: 'Modbus TCP Read-only',
    category: 'industrial-readonly',
    direction: 'ingest-readonly',
    networkEnabled: false,
    supportsWriteback: false,
    syntheticFixtureOnly: true,
    realConnectivityEnabled: false,
    fixturePath: 'config/samples/modbus-tcp-readonly-response.json',
    configValidation: true,
    normalizationSupported: true,
    envelopeSupported: true,
    localBufferSupported: true,
    deliveryPreviewSupported: true,
    auditSupported: true,
    diagnosticsSupported: true,
    productionDependencyIncluded: false,
    productionDependencyName: 'none',
    productionEnablementGate: 'Introduce gated Modbus transport and explicit write-deny enforcement before plant connectivity.',
    readinessKey: 'UFMS_EDGE_C3_04_MODBUS_TCP_READONLY_CONNECTOR_FOUNDATION_PASS',
    foundationStatus: 'foundation-ready',
  },
  {
    protocolKey: 'bacnet',
    displayName: 'BACnet/IP Read-only',
    category: 'industrial-readonly',
    direction: 'ingest-readonly',
    networkEnabled: false,
    supportsWriteback: false,
    syntheticFixtureOnly: true,
    realConnectivityEnabled: false,
    fixturePath: 'config/samples/bacnet-ip-readonly-response.json',
    configValidation: true,
    normalizationSupported: true,
    envelopeSupported: true,
    localBufferSupported: true,
    deliveryPreviewSupported: true,
    auditSupported: true,
    diagnosticsSupported: true,
    productionDependencyIncluded: false,
    productionDependencyName: 'none',
    productionEnablementGate: 'Introduce BACnet transport under broadcast control and strict WriteProperty prohibition.',
    readinessKey: 'UFMS_EDGE_C3_05_BACNET_IP_READONLY_CONNECTOR_FOUNDATION_PASS',
    foundationStatus: 'foundation-ready',
  },
  {
    protocolKey: 'opcua',
    displayName: 'OPC UA Read-only',
    category: 'industrial-readonly',
    direction: 'ingest-readonly',
    networkEnabled: false,
    supportsWriteback: false,
    syntheticFixtureOnly: true,
    realConnectivityEnabled: false,
    fixturePath: 'config/samples/opc-ua-readonly-response.json',
    configValidation: true,
    normalizationSupported: true,
    envelopeSupported: true,
    localBufferSupported: true,
    deliveryPreviewSupported: true,
    auditSupported: true,
    diagnosticsSupported: true,
    productionDependencyIncluded: false,
    productionDependencyName: 'none',
    productionEnablementGate:
      'Introduce endpoint/session controls, certificate policy, and write service denial gate before real OPC UA enablement.',
    readinessKey: 'UFMS_EDGE_C3_06_OPC_UA_READONLY_CONNECTOR_FOUNDATION_PASS',
    foundationStatus: 'foundation-ready',
  },
];

export function listC3ConnectorCapabilityMatrix(): readonly ConnectorCapabilityMatrixEntry[] {
  return MATRIX.map((entry) => ({ ...entry }));
}

export function exportC3ConnectorCapabilityMatrixSnapshot(): ConnectorCapabilityMatrixSnapshot {
  return {
    generatedAt: new Date().toISOString(),
    scope: 'c3-foundation-freeze',
    connectors: listC3ConnectorCapabilityMatrix(),
  };
}
