"""Frozen declarations for the READ_ONLY legacy Device compatibility facade."""
from enum import Enum

READ_ONLY_COMPATIBILITY_FACADE = "READ_ONLY_COMPATIBILITY_FACADE"
TEMPORARY_LEGACY_SOURCE = "TEMPORARY_LEGACY_SOURCE"
MAPPING_VERSION = "legacy-device-v1"
CONTRACT_VERSION = "1.0.0"
MAX_BATCH_SIZE = 100


class MappingDisposition(str, Enum):
    DIRECT = "DIRECT"
    NORMALIZED = "NORMALIZED"
    DERIVED = "DERIVED"
    DEFAULTED = "DEFAULTED"
    OMITTED = "OMITTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class ProjectionCategory(str, Enum):
    PROJECTED = "PROJECTED"
    PROJECTED_WITH_WARNINGS = "PROJECTED_WITH_WARNINGS"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    INVALID_SOURCE = "INVALID_SOURCE"
    SCOPE_MISMATCH = "SCOPE_MISMATCH"
    IDENTITY_CONFLICT = "IDENTITY_CONFLICT"
    PROHIBITED_FIELD_REJECTED = "PROHIBITED_FIELD_REJECTED"
